### ISSUE TITLE
Calculated field

### ISSUE THREAD

**Issue by andjelko** [unclead/yii2-multiple-input#103]
Can I add field which will be calculated from other fields?

How to do that?

**Comment by unclead** [comment]
Please elaborate what do you mean.

Something like this: https://github.com/unclead/yii2-multiple-input/blob/master/docs/tips.md#use-of-a-widgets-placeholder- ?

**Comment by andjelko** [comment]
I want to calculate total, total is price * quantity, in each row

**Comment by unclead** [comment]
The widget only provides functionality to handle multiple inputs and it cannot cover all user cases.
I guess you can achieve your aim using pre-calculation total at server side and using js for calculation total for new rows

**Comment by andjelko** [comment]
ok, thanks
