### ISSUE TITLE
Namespace

### ISSUE THREAD

**Issue by thiagotalma** [unclead/yii2-multiple-input#105]
Hello my dear, I believe you have made a mistake in changing the namespace. See the guide that is written about it.
http://stuff.cebe.cc/yii2docs/guide-structure-extensions.html#recommended-practices

Especially in this paragraph:
> Do not use `yii`, `yii2` or `yiisoft` as your vendor name. These names are reserved for use by the Yii core code.

It would be prudent to reverse the change.
Cheers!

**Comment by unclead** [comment]
thx, did read about it or read long long ago 😄 
will change a vendor name

**Comment by unclead** [comment]
fixed via 8bfc504d087489c9028036f919e3fcde7a31e952 and released a new version
