### ISSUE TITLE
New feature request: trace record deleted

### ISSUE THREAD

**Issue by Lordfef** [unclead/yii2-multiple-input#106]
Hi @unclead  , good work on 2.0 release, i solve all my problem.
I think could be very useful implement an option to trace record deleted.
For example, i have a tabular input.
User insert 10 records.
When user edit another time this model, create 2 new record and delete 2 old records.
In this case i get a post with new 10 records but i don't know that user delete 2 record. So i must write an appropriate function to compare old records with new to find the 2 records to delete.
It's hard work specially with complex models like in my case.
It' only an idea.
Thank's

**Comment by unclead** [comment]
you can try to use js event `afterDeleteRow` https://github.com/unclead/yii2-multiple-input/blob/master/docs/javascript.md to track deleted rows in a hidden input and then use it after submitting

but usually i use hidden input with id and then i am comparing records to find records which were deleted and which were added, as you described

**Comment by unclead** [comment]
Here is an example

```js
$('#examplemodel-schedule').on('afterDeleteRow', function(e, item){       
    console.log('calls on after remove row event');
   console.log('User_id:' + item.find('.list-cell__user_id').find('select').first().val());
});
```

**Comment by kwazaro** [comment]
I have the same problem when updating tabular input. How to delete rows, which were deleted by user (server-side, without javascript)? Can you please show some example code for controller?
