### ISSUE TITLE
'allowEmptyList' => true, not Delete last item

### ISSUE THREAD

**Issue by loveorigami** [unclead/yii2-multiple-input#107]
При включенной опции 'allowEmptyList' => true, не удаляется последняя запись.
Причина - не передается пустая модель.

![001](https://cloud.githubusercontent.com/assets/98164/20245225/e5f971ba-a9ad-11e6-9b70-60003917d001.png)

**Comment by unclead** [comment]
скинь на всякий случай код вьюшки для воспроизведения бага

**Comment by loveorigami** [comment]
Вьюшка самая обычная.
Связь один ко многим. Вывожу через checkboxList.
```php
<?= $form->field($model, 'group_ids')->checkboxList(ArrayHelper::map(Groups::find()->all(), 'id', 'name')) ?>
```
При сохранении без опций все работает корректно (как список сервисов).

Заменяю на MiltipleInput
```php
<?= $form->field($model, 'group_ids')->widget(MultipleInput::className(), [
        'max'               => 6,
        'min'               => 2, // should be at least 2 rows
        'allowEmptyList'    => true
    ]) ?>
```
Удаляю все строки, сохраняю, а мне возвращает последнюю строку. Как на картинке.

**Comment by unclead** [comment]
ну так ты убери `min` если хочешь чтобы можно было полностью очистить список. А то что в данном случае дает удалить это конечно бага, потому что как минимум 2 поля должны оставаться

**Comment by unclead** [comment]
Воспроизвел что ты имеешь в виду. Сходу не могу придумать красивое решение кроме как hidden поле. Надо

**Comment by loveorigami** [comment]
Да,  нужно скрытое поле.
Можешь попробовать по аналогии.
https://github.com/loveorigami/yii2-jsoneditor/blob/master/Jsoneditor.php#L61

**Comment by loveorigami** [comment]
Пришло уведомление на почту с github... 
У меня min стоит 0, это я копировал тут с доки.

**Comment by unclead** [comment]
@loveorigami если ты сделаешь PR будет здорово 😄

**Comment by Dr1N** [comment]
Использую данный модуль. Проблема существует. Последняя строка не удаляется.
Если причина известно, хотелось бы обновлённый виджет. Кто сделает фикс и PR?,

**Comment by unclead** [comment]
fixed via 53b7381acd1ab0225ebf49ab79e0359fb7ecae01

**Comment by unclead** [comment]
@Dr1N  исправлено в 35815f26c8de2e0cf793fa83bfd5259c98c4d29f
