### ISSUE TITLE
Кнопка "добавить" должна быть отдельно

### ISSUE THREAD

**Issue by SlimSavernake** [unclead/yii2-multiple-input#111]
Обычному пользователю (не редактору сайта) вообще не понятна кнопка добавить напротив первой строки. Думаю она должна быть отдельно внизу. А удалять можно любую строку, в том числе и первую. Вот нашел пример на картинке: https://github.com/synatree/yii2-dynamic-relations

**Comment by unclead** [comment]
В [документации](https://github.com/unclead/yii2-multiple-input/blob/master/docs/configuration.md) есть описание двух полезных опций:
- allowEmptyList boolean: whether to allow the empty list
- addButtonPosition integer|array: the position(s) of add button. This can be MultipleInput::POS_HEADER, MultipleInput::POS_ROW or MultipleInput:POS_FOOTER

которые решают вашу задачу.

**Comment by SlimSavernake** [comment]
Ой простите. Не прочитал ее :(
