### ISSUE TITLE
Multi input clarification

### ISSUE THREAD

**Issue by vilaskrish** [unclead/yii2-multiple-input#112]
I have written normal scripting in the form to get multiple input fields as shown below images.
Is it possible in yii2-fileapi-widget same as below.. Can u help me to do the same in multi input.

![1](https://cloud.githubusercontent.com/assets/24294507/21260720/5cd09340-c3ad-11e6-92ae-3b2238385320.PNG)
![2](https://cloud.githubusercontent.com/assets/24294507/21260738/6f45fa24-c3ad-11e6-9f9e-755450dc2c01.PNG)

**Comment by unclead** [comment]
You can use any widgets as column in multiple input widget.
If you want to have a custom markup you can write your own renderer based on TableRenderer and pass into the widget. 

```
rendererClass string: the name of renderer class. You can specify your own class to extend base functionality. Defaults to unclead\multipleinput\renderers\TableRenderer.
```

**Comment by vilaskrish** [comment]
Attached Columns are visible for first time if we use this plugin. Can we make invisible for the first time and make visible if we click button

**Comment by unclead** [comment]
if you show me your code and make a screenshot what you want to achieve it will helps me
Do you want to show file input only for all rows except a first?

Probably you have to use allowEmptyList option to achieve your goal.

Please read the docs carefully, may be you can find an answer there

**Comment by vilaskrish** [comment]
<?= TabularInput::widget([
    'models' => $admdocs,
    'attributeOptions' => [
        'enableAjaxValidation'      => true,
        'enableClientValidation'    => false,
        'validateOnChange'          => false,
        'validateOnSubmit'          => true,
        'validateOnBlur'            => false,
		'allowEmptyList'			=> true, 
    ],
	'addButtonOptions' => [
            'class' => 'btn btn-success',
            'label' => 'add' // also you can use html code
        ],
        'removeButtonOptions' => [
            'label' => 'remove'
        ],
    'columns' => [
        [
            'name'  => 'adm_stu_docs_stu_level',
            'title' => 'Title',
            'type'  => MultipleInputColumn::TYPE_TEXT_INPUT,
        ],
		[
            'name'  => 'adm_stu_docs_path',
            'title' => 'File',
            'type'  => vilas\fileapi\Widget::className(),
            'options' => [
                'settings' => [
                    'url' => ['adm-stu-docs/fileapi-upload']
                ]
            ]
        ],
        
    ],
]) ?>



I have written the code like this in a form . can u tell me how to use allowEmptyList option in this. I have researched documents and i didn't find the solution. Can u help me on this.

**Comment by unclead** [comment]
```
<?php
    echo $form->field($model, 'emails')->widget(MultipleInput::className(), [
        'max'  => 6,
        'allowEmptyList' => true,
        'columns' => [
            [
                'name' => 'emails',
                'options' => [
                    'placeholder' => 'E-mail'
                ]
            ]
        ],
        'addButtonPosition' => [
            MultipleInput::POS_HEADER,
            MultipleInput::POS_FOOTER,
            MultipleInput::POS_ROW
        ]
    ])
    ->label(false);
?>
```
