### ISSUE TITLE
Вывод данных во view, удаление пустых полей?

### ISSUE THREAD

**Issue by za4me** [unclead/yii2-multiple-input#114]
Добрый день.
Подскажите, пожалуйста, можно ли как-то используя ваш виджет удалять пустые значения автоматически перед сохранением? Что-бы не было вот такого в БД:
http://dl2.joxi.net/drive/2016/12/20/0017/0874/1139562/62/c54affc980.png
Или все-же нужно написать самому обработку в beforeSave()?

И еще небольшой вопрос по выводу данных, не совсем понял строчку в вашей документации (по выводу данных), в данный момент вывожу данный таким образом (извиняюсь за pastebin, но github почему-то криво отображает данный пример):
http://pastebin.com/RGyy5fhm
Спасибо за помощь.

**Comment by unclead** [comment]
1) Да надо самому фильтровать данные формы т.к. виджет всего лишь предоставляет функционал манипулирования данными на клиентской стороне

2) не понял вопроса по поводу вывода данных. покажите кусок view где вы используете виджет и что хотите получить на выходе

**Comment by za4me** [comment]
В DetailView атрибут:
`[
                'attribute' => 'social',
                'format' => 'raw',
                'value' => $model->socialToString(),
            ],`
В model метод socialToString()
http://pastebin.com/RGyy5fhm

На выходе получаю http://dl1.joxi.net/drive/2016/12/20/0017/0874/1139562/62/96a0149cd1.png

По виду выход устраивает, но есть сомнения верно ли я сделал socialToString.

**Comment by unclead** [comment]
А где вы используете мой виджет? 😄  причем тут DetailView и MultipleInput?

**Comment by unclead** [comment]
@za4me насколько я вижу ваш вопрос не связан с виджетом, поэтому тикет закрываю
