### ISSUE TITLE
Display multi input form only after add button click

### ISSUE THREAD

**Issue by mounicapav** [unclead/yii2-multiple-input#116]
Hi, Iam using Tabular input widget.but in that even before click of add button one row is already rendered.But I want to open form only after button click and before that it should disply only add button.Can any one help me out in this. thanks in advance.here is my code.
```
<?= TabularInput::widget([
    'models' => $admdocs,
    'attributeOptions' => [
        'enableAjaxValidation'      => true,
        'enableClientValidation'    => false,
        'validateOnChange'          => false,
        'validateOnSubmit'          => true,
        'validateOnBlur'            => false,
		'allowEmptyList'			=> true, 
    ],
	'options' => [
				'addButtonPosition' => MultipleInput::POS_HEADER,
                'allowEmptyList'    => true,
            ],
    'columns' => [
        [
            'name'  => 'adm_stu_docs_stu_level',
            'title' => 'Title',
            'type'  => MultipleInputColumn::TYPE_TEXT_INPUT,

        ],
		[
            'name'  => 'adm_stu_docs_path',
            'title' => 'File',
            'type'  => vilas\fileapi\Widget::className(),
            
        ],
        
    ],
]) ?>
```

**Comment by unclead** [comment]
you made a mistake here

```
<?= TabularInput::widget([
    'models' => $admdocs,
    'attributeOptions' => [
        'enableAjaxValidation'      => true,
        'enableClientValidation'    => false,
        'validateOnChange'          => false,
        'validateOnSubmit'          => true,
        'validateOnBlur'            => false,
		'allowEmptyList'			=> true, <--- it must be outside of attributeOptions
    ],
```

this is correct example

```
<?= TabularInput::widget([
    'models' => $admdocs,
    'attributeOptions' => [
        'enableAjaxValidation'      => true,
        'enableClientValidation'    => false,
        'validateOnChange'          => false,
        'validateOnSubmit'          => true,
        'validateOnBlur'            => false,
    ],
    'allowEmptyList'			=> true, 
```

**Comment by mounicapav** [comment]
Thanku for a very fast reply. But when i tried it it is showing an error like this  "'Setting unknown property: mounica\multiinput\TabularInput::allowEmptyList'"

**Comment by unclead** [comment]
what version do you use?

TabularInout has this property: https://github.com/unclead/yii2-multiple-input/blob/master/src/TabularInput.php#L65

**Comment by mounicapav** [comment]
<?= TabularInput::widget([
    'models' => $admedu,
    'attributeOptions' => [
        'enableAjaxValidation'      => true,
        'enableClientValidation'    => true,
        'validateOnChange'          => true,
        'validateOnSubmit'          => true,
        'validateOnBlur'            => true,
    ],
	
    'columns' => [
        [
            'name'  => 'adm_stu_edu_stu_level',
            'type'  => MultipleInputColumn::TYPE_DROPDOWN,
            'enableError' => true,
			'title' => 'Level',
            'items' =>
				ArrayHelper::map(app\modules\student\models\StuLevel::find()->where(['is_status' => 0,'level_type'=>'Education'])->all(),'level_id','level_name'),
        ],
		[
            'name'  => 'adm_stu_edu_institute',
            'enableError' => true,
			'title' => 'Institute',
        ],
		[
			'name'  => 'adm_stu_edu_specialization',
            'enableError' => true,
			'title' => 'Specialization',
		],
		[
            'name'  => 'adm_stu_edu_score',
			'enableError' => true,
			'title' => 'Score',
           
		],
		[
            'name'  => 'adm_stu_edu_year',
            'title' => 'Year',
        ],
		
	

    ],
]) ?>

	
![multi](https://cloud.githubusercontent.com/assets/23517508/21477474/391bcd76-cb68-11e6-82ec-c717669fcd67.JPG)

but still it is displaying a static form....i want that form to be displayed after clicking add....like
![multiple](https://cloud.githubusercontent.com/assets/23517508/21477493/6efa832e-cb68-11e6-8ede-2c379c4c58ab.JPG)

**Comment by unclead** [comment]
i already wrote you to use allowEmptyList like this

```
<?= TabularInput::widget([
    'models' => $admedu,
    'attributeOptions' => [
        'enableAjaxValidation'      => true,
        'enableClientValidation'    => true,
        'validateOnChange'          => true,
        'validateOnSubmit'          => true,
        'validateOnBlur'            => true,
    ],
   'allowEmptyList' => true,	
    'columns' => [
        [
            'name'  => 'adm_stu_edu_stu_level',
            'type'  => MultipleInputColumn::TYPE_DROPDOWN,
            'enableError' => true,
			'title' => 'Level',
            'items' =>
				ArrayHelper::map(app\modules\student\models\StuLevel::find()->where(['is_status' => 0,'level_type'=>'Education'])->all(),'level_id','level_name'),
        ],
		[
            'name'  => 'adm_stu_edu_institute',
            'enableError' => true,
			'title' => 'Institute',
        ],
		[
			'name'  => 'adm_stu_edu_specialization',
            'enableError' => true,
			'title' => 'Specialization',
		],
		[
            'name'  => 'adm_stu_edu_score',
			'enableError' => true,
			'title' => 'Score',
           
		],
		[
            'name'  => 'adm_stu_edu_year',
            'title' => 'Year',
        ],
		
    ],
]) ?>
```

**Comment by mounicapav** [comment]
Yes you did.but iam sorry to say that after using it only you can see the screenshot of the tabular input display like this
![multi](https://cloud.githubusercontent.com/assets/23517508/21479307/4a37f27c-cb79-11e6-9776-9dc8ae163d74.JPG)
it is getting deleted  if we delete it but on reload one row is appearing as you can see in screenshot.

**Comment by unclead** [comment]
Ok. I guess you have to use `min` option as well. Just set `'min' => 0` and you will get what you want

**Comment by mounicapav** [comment]
no...i used it as well....but then we just have a flexibility for that level....'0'

**Comment by unclead** [comment]
if it doesn't help you it means that widget doesn't cover your use case. You can make a PR or try to find another widget which will have such ability
