### ISSUE TITLE
Embedded input example does not work

### ISSUE THREAD

**Issue by execut** [unclead/yii2-multiple-input#120]
This code causes an error in the firefox after trying to add embeded input

> TypeError: data is undefined[Learn More] jquery.multipleInput.js:216:13

```php
$model = new \unclead\multipleinput\examples\models\ExampleModel();
require \yii::getAlias('@vendor') . '/unclead/yii2-multiple-input/examples/views/embedded-input.php';
```
I try it from clear yii2 basic application

**Comment by unclead** [comment]
i use inline actions for this purpose and in this case everything s ok

```
    public function actions()
    {
        return [
            'multiple' => MultipleInputAction::class,
            'embedded' => EmbeddedInputAction::class,
            'tabular' => TabularInputAction::class,
        ];
    }
```

**Comment by execut** [comment]
При попытке удалить любую строку вложенного multipleinput, в таком варианте использования, всё-равно валится похожая ошибка и удаление не происходит: TypeError: data is undefined[Learn More] jquery.multipleInput.js:295:13

**Comment by unclead** [comment]
ну а можно весь текст js ошибки, а не урезанный вариант?

**Comment by unclead** [comment]
fixed a8700f31b1a6d17dd699505f8dc200f5eecd5338
try to update to latests version

**Comment by execut** [comment]
Проверил, работает, спасибо!
