### ISSUE TITLE
Renderer of `div` s for more flexible styling

### ISSUE THREAD

**Issue by Matt182** [unclead/yii2-multiple-input#124]
is there a way in table renderer to define column width without making costume renderer or separate css file? Or more general question: Are you planing to make renderer from `div` s instead of `table` and `tr` to make it more flexible in styling?

**Comment by unclead** [comment]
I didn't plan implement such feature (i mean renderer which is based on div).
but why don't you set a width of column via css - each column has it's own css class https://github.com/unclead/yii2-multiple-input/blob/master/src/renderers/TableRenderer.php#L266 and you can use it to customize your view

Btw if you prepare a PR with rendering in DIV style it will be great. I don't have free time to implement it

**Comment by Matt182** [comment]
I try to do PR, but I am newbie, so big chance that I get it all wrong)
