### ISSUE TITLE
Issue with radio buttons

### ISSUE THREAD

**Issue by naman4488** [unclead/yii2-multiple-input#129]
Hello 

I have an issue with this widget i'm using the multi column to add an input field with a radio button when i add a row then it create a input field with a radio button and due to different name they all radios behave like checkbox.

Please give me solution to so that radio button has same name for all rows.

Thanks

**Comment by unclead** [comment]
Please, show your example of code

**Comment by naman4488** [comment]
Hello unclead
This is my code for your widget:

<?= $form->field($model, 'schedule')->widget(MultipleInput::className(), [
    'max' => 10,
    'columns' => [
        [
            'name'  => 'answer_choice',
            'enableError' => true,
            'title' => 'Answer Choice',
            
        ],
        [
            'name'  => 'Correct_ans',
            'type'  => 'radio',
            'title' => 'Correct Answer',
            
        ]
        
    ]
 ]);
?>

**Comment by naman4488** [comment]
Hello  unclead,

I'm waiting for your reply.

**Comment by unclead** [comment]
widget cannot solve your problem, but you can try to use js and checkbox to select only one correct answer
or you may try to play with `options` property and set name explicitly
