### ISSUE TITLE
Указание title, type, options без добавления columns

### ISSUE THREAD

**Issue by za4me** [unclead/yii2-multiple-input#130]
День добрый.
Подскажите, пожалуйста, могу ли я добавить для одиночного поля вышеуказанные аттрибуты? т.е. не указывая columns добавить для одиночного поля dropDownList и передать в него массив.

**Comment by unclead** [comment]
нет, а в чем проблема добавить columns?

**Comment by za4me** [comment]
Жаль. Спасибо за столь скорый ответ.
Проблемы собственно нет, но при добавлении columns поле приобретает массив вида:
`Model[field][nameColumn][0]`

А хотелось бы видеть его в виде:
`Model[field][0]`

**Comment by unclead** [comment]
переопределите класс MultipleInoutColumn (https://github.com/unclead/yii2-multiple-input/blob/master/src/MultipleInputColumn.php#L47) и укажите свой класс в настройках

**Comment by za4me** [comment]
Правильно ли я понимаю, что если будет вызов метода getElementName с $withPrefix = false то я буду получать массив вида:
`Model[field][0]`

Если да, то можно как-то из view передать false для $withPrefix? т.к. я думаю это будет лучшим вариантом чем переопределение класса.

**Comment by za4me** [comment]
Вообщем переопределять MultipleInoutColumn мне не пришлось, т.к. если имя column совпадает с именем field, то массив принимает нужный мне вид и его просто обработать each валидатором.
