### ISSUE TITLE
How to avoid duplicate records in a select

### ISSUE THREAD

**Issue by dunkel015** [unclead/yii2-multiple-input#133]
When I do a multi input I want to avoid that when one is added it is not duplicated with the one above or with another q that I select.

**Comment by unclead** [comment]
sorry but i don't understand what you want to get
provide an example please

**Comment by dunkel015** [comment]
The example I have has an entry selects and selects a field, when it is added, that the next select no longer has that field.

First select
<Select>
<Option> 1 </ option>
<Option> 2 </ option>
<Option> 3 </ option>
<Option selected = "selected"> 4 </ option>
</ Select>
Second selection when I add, and just send me from 1 to 3
<Select>
<Option> 1 </ option>
<Option> 2 </ option>
<Option> 3 </ option>
</ Select>

**Comment by unclead** [comment]
you can't achieve it using a widgets.
btw you can try to use js events for update each select after addition of a new row

the main purpose of a widget - give you ability to add several inputs with similar definition but with different values. E.g.  a list of email, phones, addresses and etc
