### ISSUE TITLE
assets error

### ISSUE THREAD

**Issue by begreeze** [unclead/yii2-multiple-input#134]
hello!
1) render a view
2) have error
syntax error, unexpected '?', expecting ']'
at line 20 of MultipleInput Asset
class MultipleInputAsset extends AssetBundle
{
    public $css = [
        YII_DEBUG ? 'css/multiple-input.css' : 'css/multiple-input.min.css'
    ];

can you help with this problem? thanks!

p.s. if write:
public $css = [
        'css/multiple-input.css'
    ];
it's ok!

**Comment by unclead** [comment]
fixed 5c51552bbd1974654f4759e7155c0554dd0b3e1d

thank you
