### ISSUE TITLE
Sort buttons

### ISSUE THREAD

**Issue by mpazaran** [unclead/yii2-multiple-input#135]
Hi

¿It is posible add buttons to sort rows?

Regards

**Comment by unclead** [comment]
you can try option `sortable` which was added in 1a0ea0aa90addec948d9c4053625700c01cf131d

**Comment by unclead** [comment]
or you mean something different?

**Comment by skrx** [comment]
Yes it is, but ... you have an issue, at yii2-multiple-input / src / components / BaseColumn.php in the line 458, I already create a pull request, I hope you like it

**Comment by unclead** [comment]
fixed via e4e94df24c902f5f33b3a0edde222b28063dcc24
