### ISSUE TITLE
При вызове виджета несколько раз на странице дублируется id поля (генерируется не уникальный id поля).

### ISSUE THREAD

**Issue by oboronitel** [unclead/yii2-multiple-input#137]
Здравствуйте.
Сразу замечу что у вас достаточно удобный виджет в своем классе)

Использую TabularInput в своем виджете, для вывода нескольких полей Select2 (http://demos.krajee.com/widget-details/select2). Эти поля выступают в роли columns. При этом возникает проблема в дублирующимся id.

При использовании в TabularInput их id перезаписываются. Необходима возможность переопределения или же добавления подстроки в Id генерируемого поля.

Пример:
id полей, находящихся в TabularInput, имеют такой вид: select2-classificationformmodel-1-code-container. Разберу по частям.

1) select2 - название класса поля из type 
2) classificationformmodel - название модели экземпляр которой передается виджету в 'models'
3) 1 -  порядковый номер строки в виджете TabularInput (он, как я понимаю, добавляется у вас в      BaseRenderer->prepareJsAttributes() )
4) code - названия поля модели ClassificationFormModel, испольуется в select2
5) container - статическая часть id

Поскольку виджет используется на одной странице несколько раз необходимо добавить дополнительный уникальный идентификатор в id. В противном случае генерируется дублирующийся id, который делает виджет неработоспособным.

В Select2 Id можно переопределить, но не могу найти где его переопределить или дополнить в TabularInput.

С уважением, Влад.

**Comment by unclead** [comment]
Я правильно понимаю, что Tabular используется в одной и той же конфигурации несколько раз на странице?

у каждой колонки есть опция `options` в которой можно указывать настройки других виджетов.

```
[
            'name'  => 'day',
            'type'  => \kartik\date\DatePicker::className(),
            'title' => 'Day',
            'value' => function($data) {
                return $data['day'];
            },
            'items' => [
                '0' => 'Saturday',
                '1' => 'Monday'
            ],
            'options' => [
                'pluginOptions' => [
                    'format' => 'dd.mm.yyyy',
                    'todayHighlight' => true
                ]
            ]
        ],
```

в примере выше в виджет датапикера передаются кастомные настройки виджета

Если вы спрашивали про это.

А лучше всего привести пример кода чтобы воспроизвести проблему тк на словах сложно представить в голове всю картину

**Comment by oboronitel** [comment]
Благодарю за скорый ответ)
Да, верно, виджет вызывается несколько раз на странице.
При этом передача опций не помогала в этом случае, так как виджет TabularInput ставил свой id.

Select2 поддерживает изменение id. Для этого необходимо передать в опции поля с Select2 параметр 'id'. Таким образом использовался новый id, который разработчик мог сам делать уникальный и подходящем ему. Но в случае использования выпадающего списка Select2 как поля TabularInput параметр id игнорировался и использовался свой способ формирования id.  

Удалось выйти из ситуации благодаря переопределению TabularColumn.
Изменение были в том что к результату getElementName добавлялся уникальная подстрока - $attribute. В нашем случае это название поля, к которому присоединен виджет Класификаторов (внутри него и используется TabularInput).

Теперь id выглядят таким образом
select2-classificationformmodel-0-code_classificationcpv-container
select2-classificationformmodel-0-code_classificationmulti-container
select2-classificationformmodel-1-code_classificationmulti-container
ранее были такие (что и приводило к дублям.):
select2-classificationformmodel-0-container
select2-classificationformmodel-0-container
select2-classificationformmodel-1-container

Так это [выглядит в интерфейсе](http://dl3.joxi.net/drive/2017/03/22/0017/1190/1152166/66/b25ed6e110.png) (2 вызова виджета выделил красным).
 
Было бы удобно если бы в опции TabularInput можно было предать еще один параметр, unicId. Который использовался бы в методе getElementName класса TabularColumn. Заменяя или же дополняя идентификатор каждого поля. Это позволило бы использовать виджет более гибко, в случае, когда его вызывают несколько раз. 

Ниже привел пример кода, в котором вызывается TabularInput с переопределением класса TabularColumn.

```
	$schemeColumn = [
		'name'  => 'scheme',
		'title' => $classificationModel->getAttributeLabel('scheme'),
		'type'  => Select2::className(),
		'items' => $settings['types'],
		'options' => [
			'disabled' => true,
			'hideSearch' => true,
			'options' => [
					'multiple' => false,
					'class'     => 'form-control classificationType'
			],
			'pluginOptions' => [
					'allowClear' => true,
			],
			'initValueText' => key($settings['types']),
			'data' => $settings['types'],
		],
	];



$tabularColumns = [
	$schemeColumn,
	[
		'name' => 'code',
		'title' => $classificationModel->getAttributeLabel('code'),
		'type' => Select2::className(),
		'options' => [
			'id' => $attribute,
			'initValueText' => $classificationDesc, // set the initial display text
			'options' => [
				'placeholder' => Yii::t('models', 'Оберіть класифікатор'),
			],
			'pluginOptions' => [
				'allowClear' => true,
				'minimumInputLength' => 3,
				'language' => [
					'errorLoading' => new JsExpression("function () { return 'Waiting for results...'; }"),
				],
				'ajax' => [
					'url' => $url,
					'dataType' => 'json',
					'data' => new JsExpression('function(params) {
					var $this=$(this);
					var type = $this.closest("tr.multiple-input-list__item").find("select:first").val();
				    console.log(type);
				    return {q:params.term,t:type}; }')
				],
				'escapeMarkup' => new JsExpression('function (markup) { return markup; }'),
				'templateResult' => new JsExpression('function(city) { return city.text; }'),
				'templateSelection' => new JsExpression('function (city) { return city.text; }'),
			],
		],
	],
];

// Hack for non-duplicate id
if(!class_exists('MyTabularColumn')) {
	class MyTabularColumn extends TabularColumn
	{
		protected static $attr = "";

		static function setAttr($attr)
		{
			self::$attr = $attr;
		}

		public function getElementName($index, $withPrefix = true)
		{
			return parent::getElementName($index, $withPrefix) . "_" . self::$attr;
		}

	}
}

MyTabularColumn::setAttr($attribute);
$tabularInputData = [
	'models'    => [$classificationModel],
	'max'       => $settings['max'],
	'min'       => 1,
	'attributeOptions' => [
		'enableAjaxValidation' => false,
		'enableClientValidation' => false,
		'validateOnChange' => false,
		'validateOnSubmit' => true,
		'validateOnBlur' => false,

	],
	'columnClass'=>MyTabularColumn::classname(),
	'columns' => $tabularColumns
];

echo TabularInput::widget($tabularInputData);
```

**Comment by unclead** [comment]
Спасибо за развернутый ответ. Надо подумать как сделать гибкое решение.
Но вы нашли правильный workaround - собственно для таких целей и была добавлена возможность переопределять классы колонок

**Comment by oboronitel** [comment]
Ясно, благодарю за внимание и вашу работу над виджетом.

**Comment by unclead** [comment]
@oboronitel реализовал как вы предложили 8bf82a0ade1175646e1b082ee20e3c9ae122ef4b
Можно обновиться до 2.8.0

добавил описание поля в вики https://github.com/unclead/yii2-multiple-input/wiki/Configuration

**Comment by oboronitel** [comment]
Позже посмотрю, как можно использовать такой вариант.
Пока оставил чуть подправленный тот переопределенный метод под себя.
Спасибо)
p.s.очень оперативно отвечаете)

```
if(!class_exists('MyTabularColumn')) {
	class MyTabularColumn extends TabularColumn
	{
		protected static $attr = "";

		static function setAttr($attr)
		{
			self::$attr = $attr;
		}

		public function getElementName($index, $withPrefix = true)
		{
			if (is_null($index)) {
				$index = '{' . $this->renderer->getIndexPlaceholder() . '}';
			}
			$elementName = '[' . $index . '][' . $this->name . ']';
			$prefix = self::$attr;
			return  $prefix . $elementName;
		}

	}
}
```
