### ISSUE TITLE
Expression is not allowed as field default value

### ISSUE THREAD

**Issue by skrx** [unclead/yii2-multiple-input#138]
In file
src/assets/MultipleInputSortableAsset.php

At line 19 you have 

`public $sourcePath = __DIR__ . '/src/';`

And it causes syntax error, unexpected '.', expecting ',' or ';'

I sugest change line 19 to 

`public $sourcePath = null;`

And initialize the value inside of the init function

**Comment by unclead** [comment]
fixed 779c7b58518768235ab28707e7411d883f9eeac3
