### ISSUE TITLE
Errors summary not showing after 10th row.

### ISSUE THREAD

**Issue by Chhoeachim** [unclead/yii2-multiple-input#139]
I don't know what's going on here. But the errors are not showing after the 10th row or more.

![capture](https://cloud.githubusercontent.com/assets/8723667/24288250/32b72bb0-10af-11e7-9fe5-dc2a870d3628.PNG)

**Comment by unclead** [comment]
fixed f3fb78c43db3e0f6345b46728a6ec1064a765eca
you have to update to 2.8.1

**Comment by Chhoeachim** [comment]
Thank @unclead .
It's work, now.

**Comment by IntegrityFoundation** [comment]
how should I update them through composer or some another way

**Comment by unclead** [comment]
via composer or download latest version as archive (i dont know what way you use)

**Comment by IntegrityFoundation** [comment]
Should I use version 2.8.1 or 2.9.0

**Comment by IntegrityFoundation** [comment]
We are supposed to remove those lines markes in pink and add those marked in green?

**Comment by unclead** [comment]
> Should I use version 2.8.1 or 2.9.0
it is up to you. Better to use last stable version (2.9)

> We are supposed to remove those lines markes in pink and add those marked in green?

i didn't understand a question, sorry

**Comment by Chhoeachim** [comment]
@IntegrityFoundation just run `composer update unclead/yii2-multiple-input`

**Comment by IntegrityFoundation** [comment]
I reinstalled the steps:
1. I entered "unclead/yii2-multiple-input": "2.9.0" in composer.json
2. And in command prompt I entered composer install.
3. Then composer update
4. And in command prompt I got foll:

  Loading composer repositories with package information
  Updating dependencies (including require-dev)
  - Installing unclead/yii2-multiple-input (2.9.0)
     Loading from cache
  Package yiisoft/yii2-codeception is abandoned, you should avoid using it. Use 
  codeception/codeception instead.
  Writing lock file
  Generating autoload files

5. And then I refereshed the page in browser to see if it is working, but it is not working.

**Comment by Chhoeachim** [comment]
Another solution:
Go to folder `web/assets` delete all folders in there. And try refresh your page again.

**Comment by IntegrityFoundation** [comment]
I deleted all the folders from web/assets and tried again, still it is not working.
