### ISSUE TITLE
is it possible to not copy a static column when you add a new row ?

### ISSUE THREAD

**Issue by michaelnguyen547** [unclead/yii2-multiple-input#144]
I have a column which show Download link. On adding new row, I do not want new row to show the Download Link, it should be blank. Is it possible ?

![2017-04-04_1759](https://cloud.githubusercontent.com/assets/436950/24684144/10f0bb9e-1961-11e7-9dfa-4e44ebdcd566.png)

**Comment by unclead** [comment]
it's not, but you can use js event `afterAdd` to achieve such behavior, e.g. you can delete a link manually

**Comment by michaelnguyen547** [comment]
thanks, man. 

Is it possible to add "row" to 'afterAddRow' ? beforeDeleteRow and afterDeleteRow has access to "row" variable. 

Right now I have to do 

```
on('afterAddRow', function(e) {
       $('#w1').find('tr.multiple-input-list__item').last().find('td.list-cell__download a').remove();
}
```

if you can add "row", it will be a lot easier

```
on('afterAddRow', function(e, row) {
       row.find('td.list-cell__download a').remove();
}
```

**Comment by unclead** [comment]
done via 0d61af5db6e8f3f8961bebc11be1def972b00dd5, you can update to 2.9.0
