### ISSUE TITLE
weird behavior when cloning row

### ISSUE THREAD

**Issue by michaelnguyen547** [unclead/yii2-multiple-input#145]
may relate to #144 

Here is my code

```
Sample Code #1
[
    'name'  => 'download',
    'title' => 'Download',
    'value' => function (\app\models\LeadStudent $data) {
        return \yii\helpers\Html::a('Download', ['lead/download-document', 'id' => $data->id]);

    },
    'type' => MultipleInputColumn::TYPE_STATIC,
    'headerOptions' => [
        'class' => 'col-md-1'
    ]
];
```
For Sample Code 1 above, when I click Add button, the Download link is cloned. 
![sample-1](https://cloud.githubusercontent.com/assets/436950/24728317/a2424dd2-1a16-11e7-8a8d-bf9b148f4848.png)

Now look at Sample Code 2

```
[
    'name'  => 'download',
    'title' => 'Download',
    'value' => function (\app\models\LeadStudent $data) {
        return ($data->document) ? \yii\helpers\Html::a('Download', ['lead/download-document', 'id' => $data->id]) : '';

    },
    'type' => MultipleInputColumn::TYPE_STATIC,
    'headerOptions' => [
        'class' => 'col-md-1'
    ]
];
```
For Sample Code 2, when I click Add button, the Download link is not cloned

No js event is running. I wonder why 
![sample-2](https://cloud.githubusercontent.com/assets/436950/24728328/aa8eac38-1a16-11e7-81c6-e11e96b56934.png)

**Comment by unclead** [comment]
It is expected behaviour. The widget generates a template based on column's definition for  rendering a new rows (e.g. https://github.com/unclead/yii2-multiple-input/blob/master/src/renderers/TableRenderer.php#L332). For generating the template we just pass an empty model (null) that is why in your case column `download` will be empty (because property is not set)

**Comment by michaelnguyen547** [comment]
I believe this is the way to solve my question #144 . Of course, the other option is to use afterAddRow event.

thanks for this awesome widget
