### ISSUE TITLE
How to use unique validation ?

### ISSUE THREAD

**Issue by vishub** [unclead/yii2-multiple-input#146]
How i can use unique validate for two column ?

`[['state_name', 'country_id'], 'unique', 'targetAttribute' => ['state_name', 'country_id']]`

show below image
![screenshot-localhost-2017-04-06-17-56-31](https://cloud.githubusercontent.com/assets/13677102/24755724/e49081b2-1af8-11e7-9bca-4c067e7bc021.png)

here the country `India` have two state `Gujarat` and `Punjab`.
when `Gujarat` state is already registered then give `Unique` error message.
how it's possible ?

**Comment by unclead** [comment]
Sorry, but validation is out of scope the widget. It is responsible only for giving an ability to add multiple input rows dynamically.

I didn't try to do what you want and so i don't have the answer for you. If you find a solution you can update tips and tricks section in wiki (it can be usefull)

**Comment by vishub** [comment]
it's ok.

But when form submit then give error and the last one inserted value show.
show below image
![screenshot-localhost-2017-04-07-10-35-50](https://cloud.githubusercontent.com/assets/13677102/24786359/7ac3008a-1b7e-11e7-8737-9e9f6a94034c.png)
what the problem ?

**Comment by unclead** [comment]
Try to check what you pass to the widget after form submitting. Frankly i don't have free time to dig deeper< try to do it by yourself. The code of widget is not so complicated to understand how exactly it works
