### ISSUE TITLE
Does the widget support multiple rows ?

### ISSUE THREAD

**Issue by michaelnguyen547** [unclead/yii2-multiple-input#147]
I have 8 fields to work with the widget. 

Row 1 has 3 fields
Row 2 has 3 fields
Row 3 has 2 fields

I am not sure how I achieve that

![sample-fields](https://cloud.githubusercontent.com/assets/436950/24821230/9f897ce2-1baa-11e7-9ed8-03f789e39633.png)

**Comment by unclead** [comment]
If you don't like a `table` style of widget you can try to use a `list` style (see wiki to get more info) or you can  implement you own renderer to get the same view as in your picture (extend from BaseRenderer and implement necessary methods by analogy with list renderer or table renderer)

If you implement flexible solution you can create a PR for it
