### ISSUE TITLE
select2 problem

### ISSUE THREAD

**Issue by zp-dima** [unclead/yii2-multiple-input#149]
In the new weighting, MultipleInput does not work with the select2 module.
The Typeahead module also does not work
When the form is loaded. When new elements of the MultipleInput are added, these modules work

Works only with version 2.6.1
```
echo $form->field($candidatesPreferredLocation, 'schedule')->widget(MultipleInput::className(), [
                            'max' => 10,
                            'allowEmptyList' => false,
                            'enableGuessTitle' => true,
                            'addButtonPosition' => MultipleInput::POS_ROW,
                            'columns' => [
                                [
                                    'type' => 'dropDownList',
                                    'name' => 'company_id',
                                    'title' => 'Preferred Company',
                                    'items' => ArrayHelper::map(\app\models\Companies::find()->all(), 'id', 'company_name'),
                                    'options' => [
                                        'prompt' => '',
//                                        'required'=>true
                                    ],
                                    'enableError' => true,
                                ],
                                [
                                    'type' => 'textInput',
                                    'name' => 'location',
                                    'title' => 'Preferred Position',
                                    'items' => [
                                        'first' => 'First',
                                        'second' => 'Second'
                                    ],
                                    'options' => [
                                        'prompt' => '',
//                                        'required'=>true
                                    ],
                                    'enableError' => true,
                                ]
                            ]
                        ])->label(false);

```

**Comment by unclead** [comment]
Any js errors in console?

**Comment by zp-dima** [comment]
http://joxi.ru/VrwV1MBIObgJnA

**Comment by unclead** [comment]
@zp-dima did you solve the problem?

**Comment by zp-dima** [comment]
no. I continue to use 2.6.1 version

**Comment by unclead** [comment]
can't reproduce.

I use this one 

```
'columns' => [
        [
            'name'  => 'user_id',
            'type'  => \kartik\select2\Select2::class,
            'enableError' => true,
            'title' => 'User',
            'defaultValue' => 33,
            /* it can be an anonymous function
            'items' => function($data) {
                return [
                    31 => 'item 31',
                    32 => 'item 32',
                    33 => 'item 33',
                    34 => 'item 34',
                    35 => 'item 35',
                    36 => 'item 36',
                ];
            }
            */
            'items' =>  [
                31 => 'item 31',
                32 => 'item 32',
                33 => 'item 33',
                34 => 'item 34',
                35 => 'item 35',
                36 => 'item 36',
            ],
            'options' => [
                'name' => 'user_id',
                'value' => '',
                'data' => [
                    31 => 'item 31',
                    32 => 'item 32',
                    33 => 'item 33',
                    34 => 'item 34',
                    35 => 'item 35',
                    36 => 'item 36',
                ],
                'options' => ['multiple' => true, 'placeholder' => 'Select states ...']
            ]
        ],
```

and it works as expected

**Comment by unclead** [comment]
closed because the author does not answer for a long time

**Comment by MadHarper** [comment]
What about init value from model?

**Comment by daniroyo** [comment]
I just test your proposed solutions and only options['data'] works as expected, items variable, with returned array or anonymous function does not work as expected, returned the internal value (id), not the text value.

For example.
'items' =>  [
                31 => 'item 31',
                32 => 'item 32',
                33 => 'item 33',
                34 => 'item 34',
                35 => 'item 35',
                36 => 'item 36',
            ],

Value at dropwdown show 31 instead of Item 31.

I show you my code.

`        <?= $form->field($model, 'users')->widget(MultipleInput::class, [
                // 'max' => 4,
                'columns' => [
                    [
                        'name'  => 'userid',
                        'type'  => Select2::class,
                        'title' => Yii::t('app', 'User'),
                        // 'items' => function($data) {
                        //     return [
                        //         3 => 'genova',
                        //     ];
                        // },
                        'items' =>  [
                            3 => 'genova',
                        ],
                        'options' => [
                            // 'data' => [
                            //     3 => 'Génova',
                            // ],
                            // 'initValueText' => function($data) {
                            //     return true ? 'Génova': '';
                            // },
                            // 'initValueText' => (!empty($user->user_id) ? $user->user->username: ''),
                            // 'value' => (!empty($user->user_id) ? $user->user_id: ''),
                            'options' => [
                                'placeholder' => Yii::t('app', 'Enter a username here...'),
                            ],
                            'pluginOptions' => [
                                'minimumInputLength' => 1,
                                'allowClear' => true,
                                'ajax' => [
                                    'url' => Url::to(['autoc']),
                                    'dataType' => Response::FORMAT_JSON,
                                    'data' => new JsExpression("function(params){ return {q:params.term}; }"),
                                ],
                                'escapeMarkup' => new JsExpression('function(markup){ return markup;} '),
                                'templateResult' => new JsExpression('function(user){ return user.username; }'),
                                'templateSelection' => new JsExpression('function (user) { return user.username || user.text; }'),
                            ],
                        ],
                    ],
                ]
            ]);
?>`
