### ISSUE TITLE
dropDownList dont work

### ISSUE THREAD

**Issue by stepancher** [unclead/yii2-multiple-input#15]
New data fine may be added, but if I have already saved the model, and open to edit in the list selected the wrong item..podozrevaju that the problem is in the model MultipleInputColumn примерно в этой строчке                 $input = Html::$type($name,null, $this->items, $options);

**Comment by unclead** [comment]
@stepancher  приведи пример кода

**Comment by stepancher** [comment]
var_dump($order->orderProducts[0]['id_product']); //возвращает '31' уже сохраненные данные
echo $form->field($order, 'orderProducts')->widget(\unclead\widgets\MultipleInput::className(), [
                        'columns' => [
                            [
                                'name' => 'id_product',
                                'value'=>31, //не важно что мы пишем сюда, есть эти поля или нет
                                'defaultValue'=>31, //не важно что мы пишем сюда
                                'title' => 'Товар',
                                'type' => 'dropDownList',
                                'items' => [
                                    '30'=>'Продукт 1',
                                    '31'=>'Продукт 2',
                                ],
                            ]
                        ]
                ]);
//В любом в dropDownList selected первый элемент из items..
//поковырявшись в вашем модуле понял что "выбранность" элемента должна задаваться selectedoption="31", но это не работает...

**Comment by stepancher** [comment]
всмысле selectedoption проставляется, но списку на него до лампочки)

**Comment by unclead** [comment]
@stepancher  Проблему воспроизвел, спасибо за репорт бага. Постараюсь исправит в ближайшее время. Если вы уже нашли решение до буду рад PR

**Comment by stepancher** [comment]
@unclead не за что! Очень полезное расширение, привет из Барнаула;)
