### ISSUE TITLE
Not Showing red error border for blank inputs

### ISSUE THREAD

**Issue by IntegrityFoundation** [unclead/yii2-multiple-input#151]
I am using unclead widget for storing multiple inputs for an attribute. In my case, User is allowed to add inputs for 5000 times, When I click on + button for adding inputs more than 10, then those inputs doesn't show red border when I left them as empty which are required as they have declared as required in validation rule.

**Comment by unclead** [comment]
try to update to latest version. This issue was already fixed (#139)

**Comment by IntegrityFoundation** [comment]
I reinstalled the steps:
1. I entered "unclead/yii2-multiple-input": "2.9.0" in composer.json
2. And in command prompt I entered composer install.
3. Then composer update
4. And in command prompt I got foll:

  Loading composer repositories with package information
  Updating dependencies (including require-dev)
  - Installing unclead/yii2-multiple-input (2.9.0)
     Loading from cache
  Package yiisoft/yii2-codeception is abandoned, you should avoid using it. Use 
  codeception/codeception instead.
  Writing lock file
  Generating autoload files

5. And then I refereshed the page in browser to see if it is working, but it is not working.


Are we supposed to make any changes in the files jquery.multipleInput.js and jquery.multipleInput.min.js?

Please provide me detail step by step process regarding how to use it in view form.
