### ISSUE TITLE
Error summary not showing below the field

### ISSUE THREAD

**Issue by vb2vish** [unclead/yii2-multiple-input#155]
extension version
"unclead/yii2-multiple-input": "~2.0"

Active form class

```
<div class="form-group">
        <?php
        echo $form->field($model, 'facility')->widget(MultipleInput::className(), [
            'max' => 1000,
            'min' => 1, // should be at least 2 rows
            'allowEmptyList' => false,
            'enableGuessTitle' => true,
            'addButtonPosition' => MultipleInput::POS_HEADER
        ])->label(false);
        ?>
    </div>
```

ITs validating form and show red bordered of textfields but label and error summery not displayed

**Comment by unclead** [comment]
you must specify 
```
enableError boolean: whether to render inline error for the input. Default to false
```

for each column which  you need an error text

Refer to wiki to get more detail about configuration options.

**Comment by vb2vish** [comment]
When i apply that attribute enableError then its give me a error
Setting unknown property: unclead\multipleinput\MultipleInput::enableError

**Comment by unclead** [comment]
You have to configure columns in this case (read manual carefully)

see an example of usage: https://github.com/unclead/yii2-multiple-input/blob/master/examples/views/tabular-input.php#L45
