### ISSUE TITLE
sortable TabularInput and delete possibility for first row

### ISSUE THREAD

**Issue by Bhoft** [unclead/yii2-multiple-input#156]
Hi first of all I would like to say thank you for this extension ;)

Now my question:
I am  using the TabularInput for collecting some Questions.
Everything works like adding new entries, saving and deleting.

Now i wanted to make the questions sortable.
I have seen that this could be enabled. So the sorting of the rows also works.

But how can I save the new order?

e.g. I have a form with 3 models (all models have a column "order")
With the original order (from the db) 1st, 2nd, 3rd. And I change the sort by moving the 3rd model above the 1st.

in _POST the models are indexed with their original position. 
`[ 2 => 3rd model, 0=>1st model, 1 =>2nd model]`

And now the 3rd model should get the new order value = 0.

My Solution currently is that after filling the models with the post data to go through the array and set the order by just incrementing with $i++, starting with $i=0;

I don't know if you do it some other way?
So hints are welcome. An example would be perfect!

---

My other problem is due to the fact that only the first row of the TabularInput gets the "+" Button it is not possible to delete it.

Only by the Sorting and changing the order I could move it to another position, saving the form and delete and save afterwards.

In my opinion the "+" Button should be on the Table top header. And the first row should also get an delete Button.

**Comment by unclead** [comment]
Hi, unfortunately i haven't used sorting feature and can't help you (it was implemented not by me)

About second question: there is issue #152 but i don't have time to fix it
