### ISSUE TITLE
Предложение по улучшению

### ISSUE THREAD

**Issue by stepancher** [unclead/yii2-multiple-input#16]
Каким-то образом, добавить возможность вместо dropDownList использовать https://github.com/RomeroMsk/yii2-chosen
с этой опцией это расширение бы покрыло 99% всех задач с мульти полями..

**Comment by unclead** [comment]
Это уже реализовано. Вот пример

```php
<?= $form->field($model, 'schedule')->widget(MultipleInput::className(), [
    'limit' => 4,
    'columns' => [
        [
            'name'  => 'user_id',
            'type'  => Chosen::className(),
            'title' => 'User',
            'options' => [
                'items' => [
                    31 => 'item 31',
                    32 => 'item 32',
                    33 => 'item 33',
                    34 => 'item 34',
                    35 => 'item 35',
                    36 => 'item 36',
                ],
                'disableSearch' => 5, // Search input will be disabled while there are fewer than 5 items
                'clientOptions' => [
                    'search_contains' => true,
                    'single_backstroke_delete' => false,
                ],
            ]
        ],
```

**Comment by stepancher** [comment]
@unclead делаю все точно так же как вы написали, но не работает...
1) сохраненный элемент не "выбран" в списке chosen
2) При нажатии на "+" добавляется строка с "поломанным chosen"
3) в консоль сыпятся ошибки js и уходят своим количеством в бесконечность..может фикс бага, сделал новый баг?)

**Comment by unclead** [comment]
обновитесь до последней версии. Все должно стать нормально

**Comment by stepancher** [comment]
@unclead  уже почти) второй и третий пункт о которых я написал пропали, но первый так и остался..сохраненный элемент не отображается "выбранным"

**Comment by unclead** [comment]
@stepancher хорошо, гляну.

**Comment by unclead** [comment]
@stepancher таки выкроил время и переписал механизм вывода строк. Теперь первый пункт должен работать корректно
