### ISSUE TITLE
How to use yii2-multiple-input widget for multiple models?

### ISSUE THREAD

**Issue by IntegrityFoundation** [unclead/yii2-multiple-input#160]
I have Employee model and Employee Work Experience model (One to many relation)

I am using dynamic form widget for this.
Can we use yii2-multiple-input for working with dynamic models?

**Comment by unclead** [comment]
i didn't try but it should

**Comment by IntegrityFoundation** [comment]
If yes, then how to use it?

**Comment by unclead** [comment]
what do you want to achieve? mb draw a sketch of what you want
