### ISSUE TITLE
How to use multiple input widget for multiple columns?

### ISSUE THREAD

**Issue by IntegrityFoundation** [unclead/yii2-multiple-input#161]
I have a scenario where we create daily task reports for employee.
We are to select Employee, date and 
we should be able to add multiple times inputs for foll fields and then similarly save it in database:
Time, Task, and Description 

Employee_______________
Date        _______________

Time _____________         Task____________          Description_________________         +
Time _____________         Task____________          Description_________________         X
Time _____________         Task____________          Description_________________         X
Time _____________         Task____________          Description_________________         X

Can you explain in detail?

**Comment by unclead** [comment]
Sorry i cant what a question is. 
Widget is only responsible for rendering view to be able use multiple rows for same inputs and it is not responsible for proper processing data after form submit.

You can use virtual property to keep form data and then save it in DB as needed.

**Comment by axklim** [comment]
https://github.com/unclead/yii2-multiple-input/wiki/Usage#multiple-columns
