### ISSUE TITLE
Remove button add and button

### ISSUE THREAD

**Issue by Maksov** [unclead/yii2-multiple-input#163]
Hello!

Need delete button "add" and "delete". Need only table with input field. How can I do? Please help

**Comment by unclead** [comment]
why don't just use a simple ActiveField instead of this widget? 😄

**Comment by Maksov** [comment]
This widget generate table (auto) auto for model with input field.
With ActiveFiled I need generate grid table with php cycle. And write other code.
I want to do simple this task

**Comment by unclead** [comment]
But this widget is designed for different issues  thus i can't help you
