### ISSUE TITLE
Need static column

### ISSUE THREAD

**Issue by Maksov** [unclead/yii2-multiple-input#164]
Hello!
I generate form

    public function actionCreate()
    {
        $modelOperation = new Operation();
        $modelKarta  = [];

        foreach (Organization::find()->all() as $org) {
            $modelKarta[$org->sono]=new Karta();
            $modelKarta[$org->sono]->id_organization = $org->id;
        }

        return $this->render('create', [
            'modelOperation' => $modelOperation,
            'modelKarta' => $modelKarta,
        ]);
   
    }

There are 12 organizations;
View
  <?= $form->field($modelOperation, 'name')->textInput() ?>
    <?= TabularInput::widget([
        'models' => $modelKarta,
        'form' => $form,
        'columns' => [
            [
                'name'=>'person',
                'title'=>'Должностное лицо'
            ],
            [
                'name'=>'period_operation',
                'title'=>'Период операции'
            ],
            [
                'name'=>'id_organization',
                'title'=>'Организация'
            ],
            [
                'title'=>'Должностное лицо, осуществляющий контрольную процедуру',
                'name'=>'person.control',
            ],
            [
                'title'=>'Контрольная процедура',
                'name'=>'name_procedure'
            ],

        ],])
    ?>

Need table.

Code Org |  Other Input Column | ... | ... | Last input column
8600                   Value_1                                   Value_n 
8601                   Value_2                                   Value_n 
8602                   Value_3                                   Value_n 
....
8624                   Value_y                                   Value_yn

How column "code org" set static and not editible?
And in model "modelKarta" there is relation id_organization. How return value to column "Code Org" from model organization?
Please help. Thanks.

**Comment by unclead** [comment]
everything is described in wiki,  also you can find something useful in https://github.com/unclead/yii2-multiple-input/blob/master/examples/views/multiple-input.php
