### ISSUE TITLE
Row Identification in TabularInput widget

### ISSUE THREAD

**Issue by fabiofolino** [unclead/yii2-multiple-input#166]
I'm looking to add some javascript to be triggered with the onblur event. Is there a way to access the row index to be used in the options array?

**Comment by unclead** [comment]
this one https://github.com/unclead/yii2-multiple-input/wiki/Tips-and-Tricks#use-of-a-widgets-placeholder ?

**Comment by unclead** [comment]
@fabiofolino is this still actual?
