### ISSUE TITLE
Add one more image to README.md

### ISSUE THREAD

**Issue by bscheshirwork** [unclead/yii2-multiple-input#168]
Readme have a first line
>Yii2 widget for handle multiple inputs for an attribute of model and tabular input for batch of models.

But in README.md have only one image for first case.

I think add [img](https://raw.githubusercontent.com/unclead/yii2-multiple-input/master/resources/images/list-renderer.jpg?raw=true) for a advanced usage to main README.md is make sense.

Первая строчка рассказывает о возможности табличного ввода моделей. Но она теряется на фоне остальной информации, основное внимание привлекает анимированный пример с вводом.

Думаю, добавление иллюстрации о возможности работы с полной моделью в README.md даст больше охват аудитории - для таких слепых, как я, которые не читают иностранные тексты, а сразу мотают до примеров :smile_cat:

**Comment by unclead** [comment]
PR is always welcome 😄
