### ISSUE TITLE
How to use to upload images

### ISSUE THREAD

**Issue by Abdul-Fattah** [unclead/yii2-multiple-input#174]
Can you help me, How to use to upload multiple (images or files) ???
using  unclead/yii2-multiple-input 
please help guys !!!

**Comment by vishub** [comment]
what you try ?

**Comment by unclead** [comment]
here is an example of usage https://github.com/vova07/yii2-fileapi-widget

https://github.com/unclead/yii2-multiple-input/blob/master/examples/views/tabular-input.php

but i can't tell you how to process data on server side after form submit because widget is responsible only for view part of code
