### ISSUE TITLE
How to show generic error message?

### ISSUE THREAD

**Issue by winternet-studio** [unclead/yii2-multiple-input#175]
My form has enableAjaxValidation=true and I'm using the Multiple columns variant and want to show a generic error message that comes back from the server. Don't want to show it for a specific input field but just in the usual place where error messages normally are shown (above or below the widget).

But only the specific inputs are in the Javascript ActiveForm list of attributes - with their IDs `[attribute]-#-[fieldname]`. But in the model validation I just want to set a generic error for `[attribute]`. How can make that show up?

If you can give me a bit of guidance maybe I can submit a PR myself if needed...

**Comment by unclead** [comment]
@winternet-studio  is it still actual?

**Comment by winternet-studio** [comment]
Yes, very much so...

**Comment by kl83** [comment]
It's important and actual for me too. In my case field is an array of related models, and it is have required validator. But no message shown when list is empty. This is my solution.

**Comment by unclead** [comment]
fixed via 2510db7ffd5d672b6d4b355655e2fbc5b51a8d1c
