### ISSUE TITLE
PHP 7.2 Cannot use yii\base\Object as Object because 'Object' is a special class name

### ISSUE THREAD

**Issue by dimmitri** [unclead/yii2-multiple-input#177]
The class name `yii\base\Object` is invalid since PHP 7.2.

In "Upgrade from Yii 2.0.12 to Yii 2.0.13":

> For compatibiliy with [PHP 7.2 which does not allow classes to be named `Object` anymore], we needed to rename `yii\base\Object` to `yii\base\BaseObject`.
>     
> `yii\base\Object` still exists for backwards compatibility and will be loaded if needed in projects that are running on PHP <7.2. The compatibility class `yii\base\Object` extends from `yii\base\BaseObject` so if you have classes that extend from `yii\base\Object` these would still work.

Class unclead\multipleinput\components\BaseColumn used yii\base\Object.

**Comment by unclead** [comment]
PR is always welcome

**Comment by unclead** [comment]
fixed via 7b79bfa60f2b2261162a5a1bd4459001a4a41973

**Comment by jithu121212** [comment]
It makes errors in forms where we use your extension.I attached the issue screenshot with it.
Thank you
Sujith
![screenshot from 2017-10-11 17-16-39](https://user-images.githubusercontent.com/24386580/31439283-35c67200-aea9-11e7-9383-1aef54f3d831.png)

**Comment by unclead** [comment]
i reverted this change until 2.0.13 will be officially released

**Comment by InsaneSkull** [comment]
@unclead [Yii2 2.0.13 released](http://www.yiiframework.com/news/149/yii-2-0-13-is-released/). Need to apply reverted pr 7b79bfa60f2b2261162a5a1bd4459001a4a41973

**Comment by unclead** [comment]
@InsaneSkull  you already did it 😄  dfeb61549c90814db35d0fb80b15ac28117efba4

**Comment by InsaneSkull** [comment]
@unclead yeah, i thought i was updating my fork. That's why.

**Comment by dromok** [comment]
In Gii similar problem.

**Comment by InsaneSkull** [comment]
@dromok Gii is not a part of this extension. Report to [Yii2-gii](https://github.com/yiisoft/yii2-gii/issues) if you have issue.
