### ISSUE TITLE
Default value for checkbox

### ISSUE THREAD

**Issue by mikbox74** [unclead/yii2-multiple-input#18]
```php
'defaultValue' => false
```
it not works for 'type' => 'checkbox'. All JS-created checkboxes always created as checked.

**Comment by unclead** [comment]
Cannot reproduce after improvements that has been made via 54653ce57e1cc5b857d182e97629a6958fddc87c

Please check it again and let me know if the issue reproduced

**Comment by mikbox74** [comment]
Thank you, it works now!
