### ISSUE TITLE
Invalid reference to yii\base\BaseObject;

### ISSUE THREAD

**Issue by dbd5** [unclead/yii2-multiple-input#180]
Hi @unclead ,

It seems your latest commit has an invalid reference to **use yii\base\BaseObject** in /src/components/BaseColumn?

Adam

**Comment by InsaneSkull** [comment]
Yii2 version? Works only on latest version.

**Comment by unclead** [comment]
i think we can set minimum required version yii2 (2.0.13) in composer.json for latest version of the widget

If you don't want to install the last version yii you can use a previous version of the widget (2.10.0)

**Comment by InsaneSkull** [comment]
@unclead I forgot to mention in PR that it require Yii2 2.0.13. My bad :(

**Comment by unclead** [comment]
I added a notice to UPGRADE.md

**Comment by unclead** [comment]
@InsaneSkull i had to revert you PR until official release of 2.0.13

**Comment by InsaneSkull** [comment]
@unclead no problem :)
