### ISSUE TITLE
Class 'yii\base\BaseObject' not found

### ISSUE THREAD

**Issue by eLFuvo** [unclead/yii2-multiple-input#181]
I'm using Yii 2.0.12 now. And there is now such class.
But classes unclead\multipleinput\components\BaseColumn, unclead\multipleinput\renderers\BaseRenderer extends by it.
So I have an error.

Maybe it should be yii\base\Object?

**Comment by unclead** [comment]
I guess you updated to latest version of the widget in which was made such change. Look at #180
You have to either update to yii2 2.0.13 or use the yii2-multiple-input 2.0.10

**Comment by unclead** [comment]
@eLFuvo  you have to update to 2.11.1
