### ISSUE TITLE
Wrong BaseObject inheritance

### ISSUE THREAD

**Issue by ElijahKaftanov** [unclead/yii2-multiple-input#182]
yii\base\ErrorException: Class 'yii\base\BaseObject' not found in .../vendor/unclead/yii2-multiple-input/src/components/BaseColumn.php:26

**Comment by unclead** [comment]
which version of widget do you use? did you read UPGRADE.md?

**Comment by unclead** [comment]
@ElijahKaftanov you have to update to 2.11.1
