### ISSUE TITLE
How to access row index?

### ISSUE THREAD

**Issue by dbd5** [unclead/yii2-multiple-input#184]
Hi @unclead ,

Is there a way to make the plugin provide certain default values for the properties by deriving them from the row value? In the configuration example below, each time a new row is created the column name will take the default value of 'column-{rowIndex}'.  The idea is that the columns will be names 'column-1', 'column-2', 'column-3' based on the row. Is there a way to do this? 

```
<?= $form->field($model, 'meta')->widget(MultipleInput::className(), [
                'max' => 4,
                'id' => 'meta',
                'allowEmptyList' => false,
                'columns' => [
                    [
                        'name'  => 'column-{rowIndex}',
                        'type'  => 'dropDownList',
                        'defaultValue' => 0,
                        'title' => 'Column {rowIndex}',
                        'items' => [...],
                        'headerOptions' => [
                            'style' => 'width: 15%;',
                        ],
                        'options' => [
                        ]
                    ],
                    [
                        'name'  => 'width',
                        'type'  => 'dropDownList',
                        'defaultValue' => 0,
                        'title' => Yii::t('backend', 'Width'),
                        'items' => [...],
                        'headerOptions' => [
                            'style' => 'width: 15%;',
                        ],
                        'options' => [
                        ]
                    ],
                    [
                        'name'  => 'source',
                        'type'  => 'dropDownList',
                        'title' => Yii::t('backend', 'Source'),
                        'items' => [...],
                        'headerOptions' => [
                            'style' => 'width: 50%;',
                        ],
                        'options' => [
                        ]
                    ],
                ]
            ])->label(false);
            ?>`

**Comment by dbd5** [comment]
Apologies - I don't know how the code lost its formatting

**Comment by unclead** [comment]
have you tried this one https://github.com/unclead/yii2-multiple-input/wiki/Tips-and-Tricks#use-of-a-widgets-placeholder ?

**Comment by dbd5** [comment]
Thanks for your response @unclead !

I did see it in the wiki but I got confused by the comment "**Ensure that you added ID of widget to a base placeholder multiple_index**" so I didn't follow through because it wasn't clear to me what you mean by adding the ID of widget to placeholder. Is it just to assign   $multiple_index = {Widget_id} ?

**Comment by dbd5** [comment]
I've managed to resolve this, here's what I did:

1. Setup row options as follows;
                'rowOptions' => [
                    'id' => 'meta-{multiple_index_multiple-input}',
                    'position' => '{multiple_index_multiple-input}',
                ],
2. Call the following expression on the **afterAddRow** event;
        $('#' + $(row).attr('id') + '-name').val('column-' + $(row).attr('position'));

**Result - the name field in each new row is assigned a value depending on the row, in this case 'column-{index}' as required**

@unclead - while this achieves my goal, could you confirm that it is in order and that it will not run afoul of future changes you plan for the plugin?

Adam

**Comment by unclead** [comment]
it's great that you fond a solution (i don't have time to check it)
I don't have a plan for further development (only if somebody will create a PR with useful feature)

**Comment by dbd5** [comment]
Great, closing this issue for now.
Please reopen if any complaints are raised

Thanks
