### ISSUE TITLE
Javascript event after sort Action

### ISSUE THREAD

**Issue by dbd5** [unclead/yii2-multiple-input#186]
Hi @unclead ,

I'd like to detect when the sortable feature has been used. Ideally a sort event needs to be triggered after the user drops a row in a new position. Could you point me in the right direction to identify and respond to the sort action?

Thanks

A

**Comment by unclead** [comment]
there is no such ability but you can check https://johnny.github.io/jquery-sortable/#docs (which is used for sorting in the widget) and add an ability to subscribe on its events

frankly i'm not so interested in further widget's development (i haven't used yii2 more then a year) and don't want to implement this feature by myself

**Comment by InsaneSkull** [comment]
@unclead I am interested in further widget's development. Can you give access to this repo?

**Comment by unclead** [comment]
@InsaneSkull sure, i sent you an invite

**Comment by InsaneSkull** [comment]
@unclead Thanks :)

**Comment by unclead** [comment]
@dbd5  did you find a solution?

**Comment by dbd5** [comment]
Hi @unclead,

I did not find a solution so I used a workaround.
In my use case, the page is built dynamically from sections that contain the widget so to achieve the required result a small javascript submits the form and reloads the page after the sort action. After the reload, the sections are in the sort order that I control via PHP

`window.sortWidgets = function(item){
        // console.log(item);
        $("#wi-section-form, #wi-page-form").submit();
    };`

 Not perfect but usable for the time being, I hope to look at this again later

**Comment by unclead** [comment]
fixed via 4b67422a6983f9c1a6e2b0f3d9dd4b8f29a39e91
