### ISSUE TITLE
No valid bower.json was found in any branch or tag of github.com/DmitryBaranovskiy/eve.git

### ISSUE THREAD

**Issue by lamabao** [unclead/yii2-multiple-input#187]
[Composer\Repository\InvalidRepositoryException] No valid bower.json was found in any branch or tag of github.com/DmitryBaranovskiy/eve.git, could not load a package from it.

**Comment by unclead** [comment]
how does it related to a widget? yii2-multiple-input doesn't have any dependency in its composer.json
