### ISSUE TITLE
Баг checkBox

### ISSUE THREAD

**Issue by stepancher** [unclead/yii2-multiple-input#19]
Снова привет, решил снова использовать твое расширение, в этот раз поле checkbox..

        'columns' => [
            [
                'name'  => 'enable_subdomain',
                'title' => 'Отображать в поддоменах?',
                'type'  => 'checkbox',
                'options'=>[
                    'class'=>''
                ],
            ],
        ]
В общем проблема в том, что каждому input в строке 182 MultipleInputColumn проставляется класс form-control... что делает отображение checkbox очень странным) думаю с другими типами аналогично..лучше бы сделать так -> если class в options указан ставить его, если нет то ставить дефолтный form-control

**Comment by unclead** [comment]
ну тут заточено под bootstrap. Если сделать как ты говоришь, то ломается обратная совместимость, ведь кто-то мог добавлять свои классы и при это полагается на то, что form-control задается автоматически.

Подумаю, что можно сделать.

**Comment by stepancher** [comment]
ну это да все правильно говоришь, просто указывая textInput(['class'=>'']) приводит к результату <input type="text" id="id.." class="" name="Model[attr]"> ,указывая textInput(['class'=>false]) приводит к результату <input type="text" id="id.." name="Model[attr]">  ожидал подобного поведения и здесь, а не тут то было) у себя то через css перекрыл все норм, решил отписаться может кому жизнь облегчит

**Comment by unclead** [comment]
Зачем закрыл? В коде действительно ошибка. Класс form-control не должен использоваться для radio и checkbox

**Comment by stepancher** [comment]
Случайно нажал "close and comment" )

**Comment by unclead** [comment]
Исправил в рамках 8db559ef2237f145666e67d3c70d4263ce4143b8
@stepancher  Проверь все ли корректно

**Comment by stepancher** [comment]
Мощный коммит. Обновил, класс пропал. Теперь опять стили править)

**Comment by unclead** [comment]
Ну а как иначе :smile: 
Ты нашел workaround, я пофиксил баг, значит надо откатить workaround
