### ISSUE TITLE
this.selector is removed in jQuery 3.0

### ISSUE THREAD

**Issue by chaimleich** [unclead/yii2-multiple-input#192]
In jquery.multipleInput.js line 78:

    id = this.selector.replace('#', '');

According the jQuery documentation, `.selector` has been deprecated since version 1.7, and as of jQuery 3.0, it is removed completely. By default, a new Yii 2.0 installation will come with jQuery 3.0+. Hence this is an acute problem.

If a proper fix will take a while to implement, I'd much appreciate at least some guidance as to how to manually change the code in our installed instances so that nothing will break.

TIA!

**Comment by unclead** [comment]
which version of widget do you use? 
in last version 2.12 there is no such line of code

**Comment by chaimleich** [comment]
You're right. I upgraded to the latest version.

Thanks
