### ISSUE TITLE
Allow empty value for column

### ISSUE THREAD

**Issue by PendalF89** [unclead/yii2-multiple-input#193]
Hello! How i can allow empty value for one of multiple columns?

**Comment by unclead** [comment]
what do you mean "empty" value? 
The widget does not check a value a column, it just provides an UI to manage values and validation of these values is has to be done on server side

**Comment by PendalF89** [comment]
`<?= $form->field($companyDraft, 'phones_array')->widget(MultipleInput::className(), [
    'max'     => 10,
    'columns' => [
        [
            'name'  => 'f',
            'title' => 'Телефон',
![2018-01-09_09-50-04](https://user-images.githubusercontent.com/5278851/34708267-8562eb24-f51a-11e7-9df1-40151058fe6a.png)

        ],
        [
            'name'  => 'i',
            'title' => 'Комментарий',
        ]
    ],
])`

How on the server side to specify that the field 'phones_array' is an array that contains a field 'i' which should be empty?

**Comment by unclead** [comment]
@PendalF89 а правила валидации то какие в модели?

**Comment by PendalF89** [comment]
Конкретно на phones_array правил нет, это поле я конвертирую в JSON и записываю в поле phones_json. Сама форма валидируется на клиенте.

**Comment by unclead** [comment]
Откуда тогда виджет вообще узнает про то что поле должно быть не пустым? Давно с yii не работал, но клиентская валидация же тоже построена на базе rules

**Comment by PendalF89** [comment]
Так я и не утверждаю, что виджет об этом узнает. Я спрашиваю как ему об этом сообщить?

**Comment by unclead** [comment]
Я не пойму что мы имеем на входе и что ты хочешь получить на выходе. В общем ты меня запутал 😄 
Если нужен пример как использовать правила валидации в связке с виджетом, то посмотри в примерах https://github.com/unclead/yii2-multiple-input/blob/master/examples/models/ExampleModel.php#L157

**Comment by PendalF89** [comment]
Смотрел уже...)
Думал, что в виджете есть встроенные средства для этого дела.
В любом случае спасибо тебе за классное расширение!
