### ISSUE TITLE
Problem with using DynamicModel

### ISSUE THREAD

**Issue by viktorsh** [unclead/yii2-multiple-input#194]
In method unclead\multipleinput\MultipleInputColumn::hasModelAttribute
Checking attribute existence, if using DynamicModel attribute. function returns false, although the attribute exists

**Comment by unclead** [comment]
if you know how to fix it - PR is always welcome

**Comment by unclead** [comment]
fixed via 122c0ed24f2b9460b1bd0e4d8e3939d478901603
