### ISSUE TITLE
Hiding the Remove button

### ISSUE THREAD

**Issue by Stern87** [unclead/yii2-multiple-input#200]
Hi!

I'm curious if it possible to hide the Remove button from some specified rows?

For example, when I'm fetching the rows from my DB source I don't want them somebody are able to delete. Instead of it, the new rows, which currently are didn't saved in the DB is possible to remove by Remove button.

Many thanks!

**Comment by unclead** [comment]
did you try to set min options depend on the amount of fetched rows?

**Comment by unclead** [comment]
@Stern87 up

**Comment by unclead** [comment]
closed due to inactivity of an issue author
