### ISSUE TITLE
Add custom html element in table cell with class list-cell__button

### ISSUE THREAD

**Issue by dimmitri** [unclead/yii2-multiple-input#202]
I wanted to add another button next to the delete button. But I can't do that.
The functions in class ListRenderer(renderActionColumn, renderRowContent) are private.

I suggest:
Add new property for class MultipleInput.
or
To make one of the functions (renderActionColumn, renderRowContent) protected.

**Comment by dimmitri** [comment]
> what for are you going to use this button?

There are many fields in the form. I wanted to click the button to open or hide optional fields of the form.

> if it is just static button without any new logic then we can introduce optional callback e.g. extraButtons, which has to return a html content

It would help me.

**Comment by unclead** [comment]
will you make a PR?

**Comment by dimmitri** [comment]
OK, I'll do PR this week.

**Comment by unclead** [comment]
@dimmitri i merged the PR. Please, don't forget to update Wiki
