### ISSUE TITLE
Add button dont work

### ISSUE THREAD

**Issue by KevinCabral** [unclead/yii2-multiple-input#205]
Hello

I update to latest version (2.14.0), but sometimes the add button works, and sometimes don't.

I made a console but no error are display.

Its happens for each case
- One column
- Multiple columns

The code:

![image](https://user-images.githubusercontent.com/8180370/37351931-acac01ec-26cb-11e8-8484-d83bb604a535.png)

![image](https://user-images.githubusercontent.com/8180370/37351881-92bb5210-26cb-11e8-8810-ebf1df9e2764.png)

**Comment by unclead** [comment]
At least you set `max` option to 4 and it means you can't have more than 4 rows. Everything else looks well and i don't see any reason for issue you faced with

**Comment by KevinCabral** [comment]
the goal is to add up to 4 lines, but the add button is not working and can not get more lines. Sometimes it works and sometimes it does not.

**Comment by unclead** [comment]
@KevinCabral  is it still relevant?

**Comment by unclead** [comment]
@KevinCabral if it is still relevant can you post a screenshot with an issue. Because everything works as expected for me

**Comment by KevinCabral** [comment]
I stopped using the extension...

Em dom, 30 de set de 2018 às 16:28, Eugene Tupikov <notifications@github.com>
escreveu:
