### ISSUE TITLE
Input base by fields table

### ISSUE THREAD

**Issue by push32** [unclead/yii2-multiple-input#210]
I have a table with 8 fields:

id, phone_one , phone_model_one, phone_signal_one, phone_two, phone_model_two, phone_signal_two

can i use multiple input to input to all fields?
Phone One - Phone Model One - Phone Signal One (+)
Phone Two - Phone Model Two - Phone Signal Two (x)

please guide me thank you so much and sorry post in here since i dont find it at wiki

**Comment by unclead** [comment]
like this? https://github.com/unclead/yii2-multiple-input/wiki/Usage#tabular-input

**Comment by unclead** [comment]
closed due inactivity of topic starter
