### ISSUE TITLE
Using multinput with select2

### ISSUE THREAD

**Issue by aguilar16** [unclead/yii2-multiple-input#211]
Hi! , sorry , I have a problem for the loading of the data in the multi input when I use the select2 widget, the data does not bring them although it is working correctly Arrayhelper :: map, diculpa for my English, I am Spanish speaking.

> [
            'type' => \kartik\select2\Select2::class,
            'name' => 'usuario_id',
            'title' => 'Usuario',
            'items' => function ($data){
                $prueba = ArrayHelper::map(User::find()->where(['estado' => 1])->all(), 'id', 'nombreCompletoCedulaDependencia');
                return $prueba;
            },
            'enableError' => true
        ],  

I'm not sure if maybe my syntax is wrong, any ideas?

**Comment by dedikisme** [comment]
For kartik select2 remove your items option and insert your data options instead options for example
`<?= $form->field($model, 'detail_pembelian')->widget(MultipleInput::className(), [
 'type'  => \kartik\widgets\Select2::className(),
'name' => 'usuario_id',
'title' => 'Usuario',
  'options' => [
                'data' => [
                1 => 'User 1',
                2 => 'User 2'
            ],
'enableError' => true
]    
]
 ]);
?>`

**Comment by vilakz** [comment]
For a multiselect within a component, a portion of the code is used
```php
 ...
        } elseif (is_array($data)) {
                $value = ArrayHelper::getValue($data, $this->name, null);
   ...
```
My decision was the code :
```php
        'columns' => [
            [
                'name' => $property->fieldName,
                'type' => Select2::class,
                'value' => function($data) {
                    return $data; // <----
                },
```

**Comment by unclead** [comment]
i think the example of @dedikisme should works in your case
```
<?= $form->field($model, 'detail_pembelian')->widget(MultipleInput::className(), [
    'type'  => \kartik\widgets\Select2::className(),
    'name' => 'usuario_id',
    'title' => 'Usuario',
    'options' => [
        'data' => ArrayHelper::map(User::find()->where(['estado' => 1])->all(), 'id', 'nombreCompletoCedulaDependencia')
    ],
    'enableError' => true
]);
?>
```

**Comment by KevinCabral** [comment]
> For kartik select2 remove your items option and insert your data options instead options for example
> 
> ```
> <?= $form->field($model, 'detail_pembelian')->widget(MultipleInput::className(), [
> 'type'  => \kartik\widgets\Select2::className(),
> 'name' => 'usuario_id',
> 'title' => 'Usuario',
> 'options' => [
>  'data' => [
>   1 => 'User 1',
>    2 => 'User 2'
>  ],
> 'enableError' => true
> ]    
> ]
>  ]);
> ?>
> ```

Work for me, thanks

**Comment by nodirbeek** [comment]
> <?= $form->field($model, 'masullar')->widget(MultipleInput::className(), [
            'id' => 'my_id',
            'allowEmptyList' => false,
            'enableGuessTitle'  => true,
            'addButtonPosition' => MultipleInput::POS_FOOTER,
            'rowOptions' => [
                'id' => 'row{multiple_index_my_id}',
            ],
            'columns' => [
                [
                    'name'  => 'masul',
                    'type'  => \kartik\select2\Select2::className(),
                    // 'type'  => Select2::classname(),
                    'title' => 'Масъул',
                    'items' => $masullar,
                    'options' => [
                    'data' => $masullar,
                        'options'=>[
                             'onchange' => <<< JS
                        $.post("pochta?cb_id=" + $(this).val(), function(data){
                            $("#subcat-{multiple_index_my_id}").val(data.pochta);
                        });
                        JS,
                       'prompt' => '================'
                        ],
                  ],
                ],
                [
                    'name'  => 'pochta',
                    'type'  => 'textInput',
                    'title' => 'Почта',
                    'items' => '',
                    'options'=> [
                        'id' => 'subcat-{multiple_index_my_id}'
                    ],
                ],
            ]
    ])->label(false);
    ?>
