### ISSUE TITLE
How to set initValueText for exitsing record in Select2 column?

### ISSUE THREAD

**Issue by soap** [unclead/yii2-multiple-input#214]
I had one column as Select2 and if record already exists it shown id instead of name. How to set InitValueText for Select2?

        [
            'name' => 'student_id',
            'title' => 'Student ID',
            'enableError' => true,
            'type' => \kartik\select2\Select2::class,

            'options' => [
                'initValueText' => function($data) { return $data->student->fullName; },
                'pluginOptions' => [
                    'allowClear' => true,
                    'minimumInputLength' => 2,
                    'ajax' => [
                        'url' => Url::to(['class/list-student']),
                        'dataType' => 'json',
                        'delay' => 250,
                        'data' => new JsExpression('function(params) { return {class_id: '.$modelClass->id.', q: params.term, page: params.page}; }'),
                        'processResults' => new JsExpression($resultsJs),
                        'cache' => false
                    ],
                    'escapeMarkup' => new JsExpression('function (markup) { return markup; }'),
                    'templateResult' => new JsExpression('formatStudent'),
                    'templateSelection' => new JsExpression('formatStudentSelection'),
                ],
            ]
        ],
`
The above initValueText did not work. Please help. Thanks.

**Comment by soap** [comment]
Ok I got the solution to display student name. Just pass $data as array of id, name.

**Comment by soap** [comment]
How can I access each model attribute? I want to set initValueText for Select2. The above solution works but is it ok?

**Comment by unclead** [comment]
@soap i guess it is not still relevant but if so the solution is use a callback as value for `options`

```
'options' => function($model) {
    return [
         'initValueText'=> $model ? $model->studen->fullName : '',
         ...
         ...
   ]   
```

In this case you will get real value for existing rows and an empty value for every new row because empty model is passed when widget generates a template for new row
