### ISSUE TITLE
Programmatically change the elements via js

### ISSUE THREAD

**Issue by vilakz** [unclead/yii2-multiple-input#219]
Hi,
I must fill an items with previously saved data.
call $element.multipleInput('clear') - all rows are deleted, except the first. Where the Add button is located.
through  $element.multipleInput('add', {values}) add the lines, but in the very first I can not change the values

methods that change the arbitrary value I did not find. 
Is there any solution?

**Comment by unclead** [comment]
there is no such js method, because it is assumed that already saved data is used on server side to render the widget
