### ISSUE TITLE
ajax validation trouble via ListRenderer when entered an incorrect value

### ISSUE THREAD

**Issue by phrakon** [unclead/yii2-multiple-input#220]
When i use TableRenderer with multiple columns the widget works fine, but if i change rendererClass property to ListRenderer (nothing more) i watch red border around input field (it is OK) but no error message present. Ajax response is OK, TableRenderer prove it. What's wrong?

Update: I use $form->field($model, 'addresses')->widget(MultipleInput::className(),...
instead of <?= TabularInput::widget([... in your demo

**Comment by phrakon** [comment]
i found solution:
ListRenderer.php:233
must be like $content .= Html::tag('div', $input."\n" . $column->renderError($error), $wrapperOptions);

**Comment by unclead** [comment]
@antkaz can you help us with it?

**Comment by antkaz** [comment]
Hello. I'll see how time will turn out.

**Comment by antkaz** [comment]
@phrakon is there a similar problem in version 2.14?

**Comment by antkaz** [comment]
I found a mistake. This is due to the fact that the container is given the wrong layout.

Now:
```html
<div class="form-group list-field">
    <label class="col-lg-4 control-label" for="model-0-field">title</label>
    <div class="field-model-0-name col-lg-8">
        <input type="text" id="model-0-field" class="form-control" name="Model[0][field]" aria-invalid="true">
    </div>
    <div class="help-block help-block-error col-lg-offset-4 col-lg-8"></div>
</div>
```

should be

```html
<div class="form-group field-model-0-name list-field">
    <label class="col-lg-4 control-label" for="model-0-field">title</label>
    <div class="col-lg-8">
        <input type="text" id="model-0-field" class="form-control" name="Model[0][field]" aria-invalid="true">
    </div>
    <div class="help-block help-block-error col-lg-offset-4 col-lg-8"></div>
</div>
```
The fact is that the yii.activeform.js can not find the container to which the error message will be added

https://github.com/yiisoft/yii2/blob/master/framework/assets/yii.activeForm.js#L717

I can fix this error and create a PR

**Comment by InsaneSkull** [comment]
@antkaz PR will be great
