### ISSUE TITLE
Max, Min rows based on 2 activeFields

### ISSUE THREAD

**Issue by ered15** [unclead/yii2-multiple-input#224]
Hi, was wondering if anyone knows of a way to limit max, min rows based on 2 id's, the idea is to change value of min max depending if i add a row on other field, was thinking it could be something triggered on afterAddRow event.

**Comment by unclead** [comment]
you can try to change the widget options in an event handler using this one https://github.com/unclead/yii2-multiple-input/wiki/Javascript-events#option
