### ISSUE TITLE
daterangepicker is not defined TabularInput

### ISSUE THREAD

**Issue by ered15** [unclead/yii2-multiple-input#225]
Hi,i'm getting this error `ReferenceError: daterangepicker_9859142c is not defined` when using `'type'  => DateRangePicker::classname(),` in a column inside `TabularInput::widget()` anyone know why?

**Comment by ered15** [comment]
Think is a similar issue to: https://github.com/unclead/yii2-multiple-input/issues/215 just to be clear the issue only happens when using TabularInput::widget()

**Comment by unclead** [comment]
duplicate of #215
