### ISSUE TITLE
Replacing Glyphicons with Fontawesome

### ISSUE THREAD

**Issue by dbd5** [unclead/yii2-multiple-input#228]
Hello @unclead ,

Seeing glyphicons are dropped from bootstrap 4 and and fontawesome works well with bootstrap 3 and 4, would you consider replacing glyphicons with fontawesome in this project?

Adam

**Comment by InsaneSkull** [comment]
@dbd5 If you have time. Would you like to add a PR?

**Comment by InsaneSkull** [comment]
@unclead Your thoughts?

**Comment by unclead** [comment]
we can add support of fontawesome, then wait couple releases and then get rid of glyphicons.

**Comment by dbd5** [comment]
Ok, I will look into it

**Comment by unclead** [comment]
closed via 3c84bc5ee717d3fd687adb11d3017fc7e48beecc
