### ISSUE TITLE
isRendererHasOneColumn considers sortable column added by MultipleInput::createRenderer

### ISSUE THREAD

**Issue by phrakon** [unclead/yii2-multiple-input#229]
In the case i expect a column and dont't want to render it's name.

https://github.com/unclead/yii2-multiple-input/blob/556a3fb2cb1f063ca47640a49b6d481c89175c5f/src/MultipleInputColumn.php#L72

**Comment by phrakon** [comment]
And hidden columns has not to be added to sortable column

**Comment by unclead** [comment]
@phrakon sorry but i didn't get what you mean.
May be better to attach an example of code and some screenshots?

**Comment by unclead** [comment]
closed due to inactivity of issue reporter

**Comment by phrakon** [comment]
Здравствуйте! Речь шла о том, что если я использую виджет в режиме одного столбца и хочу чтобы элементы были перетаскиваемые, то метод isRendererHasOneColumn в этом случае возвращает false так как виджет автоматически добавляет слева фейковый столбец для перетаскивания элементов. isRendererHasOneColumn должен не учитывать DragColumn

**Comment by phrakon** [comment]
Что интересно,  в демке этот момент не работает
http://skrinshoter.ru/s/241219/I4PKi9MS
http://skrinshoter.ru/s/241219/Bb2g3C5v
http://skrinshoter.ru/s/241219/8CJkRf8a
