### ISSUE TITLE
Problem for Widget Id with upper case

### ISSUE THREAD

**Issue by Yannn** [unclead/yii2-multiple-input#234]
In JS configuration **projectUsers**
`jQuery('#projectUsers').multipleInput({"id":"projectUsers"...`
NO in template **projectusers**
`"template":"<tr ... id=\"project-projectusers-{multiple_index_projectusers}-project_id\"`
In result on add action:

> Error: Syntax error, unrecognized expression: #project-projectusers-{multiple_index_projectusers-widget}-project_id

**Comment by unclead** [comment]
it is a default behaviour of Yii2 to cast ID to lower case
~~~
    public static function getInputId($model, $attribute)
    {
        $name = strtolower(static::getInputName($model, $attribute));
        return str_replace(['[]', '][', '[', ']', ' ', '.'], ['', '-', '-', '', '-', '-'], $name);
    }
~~~

and we can't do anything with it
