### ISSUE TITLE
The extension adds two clones with same numerical ID's

### ISSUE THREAD

**Issue by mikbox74** [unclead/yii2-multiple-input#236]
![image](https://user-images.githubusercontent.com/1404546/45360954-9ceb5800-b5d9-11e8-8f7c-f51ff242cf6a.png)

I have pre-populated form and a list of identical controls.
When I press + button to add new one, it appears but have same numerical ID as last control have, e.g. 6.
When I add one more it has different ID, e.g. 7.
```php
    <?= $form->field($model, 'settings')->widget(MultipleInput::class, [
        'columns'  => [
            [
                'enableError' => true,
                'name'  => 'settings',
                'type'  => 'dropDownList',
                'items' => $plugin::getColumns(),
            ],
        ],
    ])->hint('COLUMNS_SETTINGS_HINT') ?>
```

**Comment by mikbox74** [comment]
May be you must remove any control in the middle to reproduce the bug

**Comment by unclead** [comment]
@mikbox74 is it still relevant?

**Comment by mikbox74** [comment]
Yes, it is.

**Comment by unclead** [comment]
@mikbox74  i need more details to reproduce the issue. 
What is hidden for `$plugin::getColumns()`? 
Also it would be great to see you model and what it contains.

First step to fix the issue - reproduce it 😄

**Comment by mikbox74** [comment]
https://github.com/mikbox74/multiple-input-test

A sandbox example project where you can see the bug in action

**Comment by unclead** [comment]
@mikbox74 to be honest i don't know how to solve this issue. 

Widget can't properly handle the case when input data has custom indices (in your case indices are not sequential). 

Now the widget just gets the number of rows and increment this value each time new row is added.
In your example current rows have indices 0,1,3 and you expect to get 4 when add new row. 
I guess we can detect that each index has a numeric value and use max value as initial current index.

But what if i remove the row with index 3. Should the new row has an index 2 or 3? It seems so complicated for me.

I can add a callback which will be called each time new rows is added and you can implement your own logic using this callback.

**Comment by mikbox74** [comment]
@unclead I guessed the index will be greatest free, e. g. 0,1,3 - new index is 4; 1,3,4,5,7,8 - new index is 9 etc. If you find it's complicated or illogical, no problem. I can use array_values() before my forms saving.

**Comment by unclead** [comment]
i suggest to use `array_values`
