### ISSUE TITLE
Add custom button nearby "add button or clone button"

### ISSUE THREAD

**Issue by 112Legion112** [unclead/yii2-multiple-input#237]
I need to add a button that will do custom logic in rows. 

Here an example how it should look like. 

![image](https://user-images.githubusercontent.com/20613430/45404287-b8a53b80-b677-11e8-8baf-53afd1dc69e9.png)

Is there a way how to do it?

**Comment by unclead** [comment]
you can use the option `extraButtons` (you can get more details in wiki)

**Comment by 112Legion112** [comment]
@unclead it's only available for "MultipleInput" but widget "TabularInput" doesn't have this future.

**Comment by unclead** [comment]
@112Legion112  you can make a PR for adding a support of this option in TabularInput
