### ISSUE TITLE
Extract Json Data

### ISSUE THREAD

**Issue by deshario** [unclead/yii2-multiple-input#238]
How to extract email and Schedule data ... for gridview,detailview and normal php ...

![extract](https://user-images.githubusercontent.com/11426727/46426022-8d3dda00-c767-11e8-8761-13f19b4a5017.PNG)

**Comment by unclead** [comment]
Why do you ask it here?
it is out of scope of the widget responsibility

But I guess you have to decode json in afterFind method

**Comment by deshario** [comment]
When i use afterfind in my model it error like this
Error
![error](https://user-images.githubusercontent.com/11426727/46428388-07715d00-c76e-11e8-906a-9282b7083e92.PNG)

Demo
![demo](https://user-images.githubusercontent.com/11426727/46428404-122bf200-c76e-11e8-8121-a99cf14e29ea.PNG)

Can u recommend me how to get out of this problem ... Thankx Very Much

**Comment by unclead** [comment]
@deshario better to ask general questions on the official forum or in the [gitter chat room](https://gitter.im/yiisoft/yii2)
