### ISSUE TITLE
Backward compatibility has been broken 

### ISSUE THREAD

**Issue by phrakon** [unclead/yii2-multiple-input#239]
composer.json has "php": ">=5.4.0", but you use 
https://github.com/unclead/yii2-multiple-input/blob/d28cbeb7c821eff58a8236cbe786d0da1e40170a/src/components/BaseColumn.php#L532
that's not good. My code doesnt work after update (yes, i use 5.4 :))

**Comment by unclead** [comment]
fixed in 2.17.1
