### ISSUE TITLE
Uploading File Issue

### ISSUE THREAD

**Issue by deshario** [unclead/yii2-multiple-input#242]
I tried to upload multiple files by clicking into + icon ... but it always returns null ... Is there anyway that we can save multiples files via using kartik inputfile

**Controller**
 
>    $data  = Yii::$app->request->post();

> foreach($data as $index => $item) {
                    $object = new Project();
                    $object->load($item);
                    $file = UploadedFile::getInstance($object, "[$index]mfile");
                    var_dump($file); // return Null, Null
                }

> foreach($data['Project']['aa'] as $key => $val) {
    $choice = $val['mchoice'];
    $file = $val['mfile'];
    $UploadedFile = UploadedFile::getInstances($model, $file);
    var_dump($UploadedFile); // return null
}

**View**
> 
       <?= $form->field($model, 'aa')->widget(MultipleInput::className(), [
            'max' => 4,
            'columns' => [
                [
                    'name'  => 'mchoice',
                    'type'  => 'dropDownList',
                    'title' => 'File Type',
                    'defaultValue' => 1,
                    'items' => [
                        1 => 'type1',
                        2 => 'type2',
                        3 => 'type3',
                    ]
                ],
                [
                    'name' => 'mfile',
                    'type' => FileInput::className(),
                    'options' => [
                        'pluginOptions' => [
                            'initialPreview'=>[
                                //add url here from current attribute
                            ],
                            'showPreview' => false,
                            'showCaption' => true,
                            'showRemove' => true,
                            'showUpload' => false,
                        ]
                    ]
                ],
            ]
        ])->label(false); ?>

**Comment by bscheshirwork** [comment]
@deshario try to use https://github.com/zxbodya/yii2-gallery-manager for your case?

**Comment by asilvestre87** [comment]
@deshario, Could you do it? I can save images but after, i can't show it in the widget...

**Comment by unclead** [comment]
@deshario is it still relevant?

**Comment by deshario** [comment]
@asilvestre87  can i have a look at your example
