### ISSUE TITLE
MultipleInput and layoutConfig

### ISSUE THREAD

**Issue by numitec** [unclead/yii2-multiple-input#244]
Hello there,

  I recently downloaded version 2.17.1 and I'm trying to set layoutConfig:
  
```
$form->field( $model, 'rules')->label(false)->widget(MultipleInput::className(), [
	'max' => 8,
	'layoutConfig' => [
		'offsetClass' => 'col-sm-offset-0',
		'labelClass' => '',
		'wrapperClass' => 'col-sm-10',
		'errorClass' => ''
	],
        ...
```

  But it seems I'm doing something wrong; when I inspect the resulting html I see:

```
<div class="form-group field-policy-rules">
   <div class="col-sm-6 col-sm-offset-3">
   <input type="hidden" name="Policy[rules]">

```

  Any clues? Thanks!

**Comment by unclead** [comment]
you didn't post the whole code thus i don't know what renderer you use, but I have to remind that layoutConfig is currently supported only by ListRenderer and it is said in wiki

> layoutConfig array: CSS grid classes for horizontal layout (only supported for ListRenderer class). This must be an array with these keys:

**Comment by unclead** [comment]
@numitec please read the docs before asking a question (https://github.com/unclead/yii2-multiple-input/wiki/Configuration)
Default renderer is TableRenderer not ListRenderer

**Comment by numitec** [comment]
Sorry, I'm new at Yii2, too.

I solved using this attributes when calling the form:

```
 <?php
		$form = ActiveForm::begin([
			'layout' => 'horizontal',
			'fieldConfig' => [
				'horizontalCssClasses' => [
					'label' => 'col-sm-3',
					'offset' => 'offset-sm-4',
					'wrapper' => 'col-sm-12',
				]
			]
		]);
	?>
```
