### ISSUE TITLE
Add property to allow use widget outside the form and make createRenderer() method protected (instead private)

### ISSUE THREAD

**Issue by Matvik** [unclead/yii2-multiple-input#245]
There is no field in MultipleInput class to setup hiddeninput attributes (i want to use widget outside of the main form, so is has to be set "form" attribute in hidden input). 
And i can`t rewrite "run()" method in my own class, because it uses "createRenderer()" method, witch is private (instead protected).

Thanks!

**Comment by Matvik** [comment]
Sorry, it looks like any other inputs in widget must have "form" attribute to work outside the form.

**Comment by unclead** [comment]
what do you mean `outside the form`?

**Comment by unclead** [comment]
@Matvik up

**Comment by Matvik** [comment]
Sorry for long answering. I mean this attribute:
[https://www.w3schools.com/tags/att_input_form.asp](https://www.w3schools.com/tags/att_input_form.asp)

**Comment by unclead** [comment]
1) you can use the widget without outside form
```
  echo MultipleInput::widget([
        'name' => 'emails',
        'data' => [
            ['emails' => 'test@test.com'],
            ['emails' => 'test2@test.com']
        ],
        'max'  => 6,
        'allowEmptyList' => false,
        'sortable' => true,
        'columns' => [
            [
                'name' => 'emails',
                'options' => [
                    'placeholder' => 'E-mail'
                ]
            ]
        ],
        'min'  => 2, // should be at least 2 rows
        'addButtonPosition' => [
            MultipleInput::POS_HEADER,
            MultipleInput::POS_FOOTER,
            MultipleInput::POS_ROW
        ]
    ]);
```

all you have to do is just to set extra options `name` and `data`

2) method `createRenderer` has been changed to protected 311e5d229e625c918c83952c1aa647083845c76d
