### ISSUE TITLE
Как правильно отображать выведеные результаты при использовании нескольких выпадаюших списков Select2

### ISSUE THREAD

**Issue by Sirgalas** [unclead/yii2-multiple-input#248]
собсвено вот код 

```
<?= $form->field($model->publicPartners, 'partners')->widget(MultipleInput::class, [
        //'max' => 1,
        'columns' => [
            [
                'name'  => 'partners',
                'type'  => Select2::class,
                'title' => false,
                'options' => [
                    'data'=>CompanyService::getAllIdName(),
                    'options'=>[
                        'placeholder' => Yii::t('backend','Select Public Partners'),
                    ],
                    'language' => 'ru',
                    'pluginOptions' => [
                        'allowClear' => true,
                    ],
                ],
                'items' => [
                    $model->publicPartners->partners,
                ]
            ],
            [
                'name'  => 'roles',
                'type'  => Select2::class,
                'title' => false,
                'options' => [
                    'data'=>RolePartnerService::getAllIdName(),
                    'options'=>[
                        'placeholder' => Yii::t('backend','Select Role'),
                    ],
                    'language' => 'ru',
                    'pluginOptions' => [
                        'allowClear' => true,
                    ],
                ],
                'items' => [
                    $model->publicPartners->roles,
                ]
            ],
        ]
    ])->label(Yii::t('backend','Public Partners'));
    ?>
```

где у этой модели `$model->publicPartners` есть два свойства partners (здесь id сушности Partners) и roles (здесь id сушности Roles) которые я пытаюсь заполнять. Вот здесь   `$model->publicPartners->partners`, и здесь `$model->publicPartners->roles`, вывожу id  этих сушностей (по связи многие ко многим). Вот такое значение получаются` $model->publicPartners->partners = array(0=>1), $model->publicPartners->roles=array(0=>1)`. Объектов partner много (и id может быть множество)  а ролей всего две. 
    При сохранении проблем не возникает но вот если после этого зайти в редактирования получается проблема с отображением. 
Если выбран первый партнер при этом все равно какой id будет (у меня id первого партнера равен 5) 
то выберется отобразиться перавая роль (при этом все равно что будет в `$model->publicPartners->roles` если выбереться второй партнер отобразиться вторая роль. Если третий партнер и далее то роли вообше не отобразятся поскольку их две).
Вопрос что делаю не так ?

**Comment by bscheshirwork** [comment]
@Sirgalas у вас совпадает имя атрибута модели и имя первого столбца, отображаемого виджетом. Используйте другое свойство модели для добавления виджета:
```php
<?= $form->field($model->publicPartners, 'partners')->widget(MultipleInput::class, [
...
        'columns' => [
            [
                'name'  => 'partners',
...
            [
                'name'  => 'roles',
```

```php
<?= $form->field($model->publicPartners, 'anotherNameField')->widget(MultipleInput::class, [
...
        'columns' => [
            [
                'name'  => 'partners',
...
            [
                'name'  => 'roles',
```

**Comment by bscheshirwork** [comment]
p.s.:Данная ситуация с непониманием возникает по той причине, что поведение для единственного и для множественных заданий столбцов отличается. Возможно, стоит обратить на это внимание в примере  использования (т.к. дальше никто не читает, а пример всё равно не полный)
@unclead

**Comment by Sirgalas** [comment]
Да я уже ответ нашел собствено вот здесь https://github.com/unclead/yii2-multiple-input/wiki/Usage#multiple-columns
