### ISSUE TITLE
Ошибка при обновлении до 1.2.0

### ISSUE THREAD

**Issue by stepancher** [unclead/yii2-multiple-input#25]
подключаю примерно так
<?= $form->field($model, 'subservices')->widget(\unclead\widgets\MultipleInput::className(), [
'columns' => [
                        [
                            'name'  => 'name',
                            'title' => 'Доп.Услуга',
                            'type'=>'textInput',
                        ],
....
]?>
имена полей раньше были что-то вроде Service[subservices][0][name], то теперь Service[0][name]. Толи бага толи фича..но у меня все сломала, откатился до 1.1.0 все норм

**Comment by stepancher** [comment]
ах да и пустой массив перестал кушать..если  $model->subservices = [] то раньше обозначало что записей нет, и рисовалось пустое поля мол ввести надо, теперь ексепшн..

**Comment by unclead** [comment]
приведи весь пример с моделью и вьюхой и оформи с помощью mardown, чтобы можно было легко код прочитать

**Comment by stepancher** [comment]
Писал в полночь, уставший очень..суть в том что у модели есть атрибут subservices к которому подключаю виджет как в README, раньше имена полей содержали имя атрибута теперь нет.

**Comment by unclead** [comment]
ничего не понял. Приведи пример нерабочего кода, чтобы я мог воспроизвести ошибку и исправить. Те примеры на которых я делал работают корректно

**Comment by unclead** [comment]
@stepancher http://prntscr.com/89sm8t вот смотри все нормально подставляется. В общем жду от тебя полного примера кода для воспроизведения ошибки

**Comment by unclead** [comment]
> ах да и пустой массив перестал кушать..если $model->subservices = [] то раньше обозначало что записей нет, и рисовалось пустое поля мол ввести надо, теперь ексепшн..

Это исправил в мастере 8a1d44b71790fc7a9fa028589199d37e2a38249d

**Comment by unclead** [comment]
Закрываю за отсутствием информации и невозможностью воспроизвести ошибку 
> имена полей раньше были что-то вроде Service[subservices][0][name], то теперь Service[0][name]. Толи бага толи фича..но у меня все сломала, откатился до 1.1.0 все норм

второй пункт был исправлен

**Comment by stepancher** [comment]
Был в отпуске, забыл отписаться..сейчас все работает, здесь https://github.com/unclead/yii2-multiple-input/issues/27 человек описал ту же проблему, и теперь префиксы генерируются правильно;)
