### ISSUE TITLE
Как загружать изображения в yii2-multiple-input

### ISSUE THREAD

**Issue by artursharipov** [unclead/yii2-multiple-input#262]
![default](https://user-images.githubusercontent.com/28647089/50467580-8b319300-09c5-11e9-86ac-2a07072d123b.PNG)
Нужно чтобы при отправке формы отправлялись прикрепленные файлы. В контроллер приходит только название файла и всё.
` <?= $form->field($model, 'plan')->widget(\unclead\multipleinput\MultipleInput::className(), [
                //'max' => 4,

                'columns' => [
                    [
                        'name'  => 'planImage',
                        'title' => 'Картинка плана этажа',
                        'type'  => 'fileInput',
                        
                    ],
                    [
                        'name'  => 'planRange',
                        'title' => 'Диапозон этажей',
                        
                        'enableError' => true,
                        'options' => [
                            'class' => 'input-priority'
                        ]
                    ]
                ]
            ]);
        ?>`

**Comment by InsaneSkull** [comment]
How you are getting post data in controller? Add controller code

**Comment by artursharipov** [comment]
here I need to get the files and save to the site. but they are not even coming to the controller. Only file names come
`public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {
            
            //here I need to get the files and save to the site. but they are not even coming to the controller. Only file names come

            print_r($model->plan); //Array ( [0] => Array ( [planImage] => 1.PNG [planRange] => ) )
            
            if($model->save()){
                return $this->redirect(['view', 'id' => $model->id]);
            }
            
        }        

        return $this->render('update', [
            'model' => $model,
        ]);
    }`

**Comment by artursharipov** [comment]
maybe there is just a ready-made example of sending files with the fileinput type?

**Comment by artursharipov** [comment]
thank you
