### ISSUE TITLE
MaskInput lack of clientOptions

### ISSUE THREAD

**Issue by ruslan-immunity** [unclead/yii2-multiple-input#265]
```
'clientOptions' => [
        'alias' =>  'url',
    ],
```
нет возможности сделать маску для URL
Также при использовании стилей - стили игнорируются
```
'columns' => [
        ...
        [
            'name'  => 'phones',
            'title' => $model->getAttributeLabel('phones'),
            'type' => \yii\widgets\MaskedInput::className(),
            'options' => [
                'class' => 'input-phone',
                'mask' => '999-999-99-99',
            ],
        ],
    ],
```

**Comment by unclead** [comment]
А вы документацию читаете прежде чем задать вопрос? Например, самый базовый пример https://github.com/unclead/yii2-multiple-input/wiki/Basic-scenario-of-usage в котором видно, что для плагинов надо использовать `pluginOptions`

**Comment by ruslan-immunity** [comment]
> А вы документацию читаете прежде чем задать вопрос? Например, самый базовый пример https://github.com/unclead/yii2-multiple-input/wiki/Basic-scenario-of-usage в котором видно, что для плагинов надо использовать `pluginOptions`

https://github.com/unclead/yii2-multiple-input/wiki/Configuration

**Comment by ruslan-immunity** [comment]
зачем тогда в конце описания дан неверный пример? https://github.com/unclead/yii2-multiple-input/wiki/Configuration

**Comment by unclead** [comment]
вот такое работает
```
              'title' => $model->getAttributeLabel('phones'),
                'type' => \yii\widgets\MaskedInput::className(),
                'options' => [
                    'mask' => '999-999-99-99',
                    'options' => [
                            'class' => 'input-phone'
                    ]
                ],
```

**Comment by ruslan-immunity** [comment]
спасибо
