### ISSUE TITLE
Make registerJsSortable() is protected

### ISSUE THREAD

**Issue by bscheshirwork** [unclead/yii2-multiple-input#268]
I wish to redefine options of `jQuery` `sortable` in `ListRenderer` but I can't change a 
https://github.com/unclead/yii2-multiple-input/blob/d9b054229adae812062a1ebaec4318480b62c068/src/renderers/BaseRenderer.php#L427-L451

call in  public function render()
https://github.com/unclead/yii2-multiple-input/blob/d9b054229adae812062a1ebaec4318480b62c068/src/renderers/BaseRenderer.php#L420-L422

I

**Comment by unclead** [comment]
done 4489740067a8ae76b9bb8c099e12731bd0b383ca
