### ISSUE TITLE
Ошибка гинерации префикса

### ISSUE THREAD

**Issue by fiamma06** [unclead/yii2-multiple-input#27]
Инициализирую виджет:
``````
<?= $form->field($model, 'phone')->widget(MultipleInput::class) ?>
``````

При этом префикс создается не корректно:
```
<input type="text" id="representation-phone-phone-1" class="form-control" name="Representation[phone][phone][1]" value="asdfasdf">
```

Если я правильно понимаю результат должен быть:
``````````
<input type="text" id="representation-phone-1" class="form-control" name="Representation[phone][1]" value="asdfasdf">
``````````
Проблема наблюдается только в случае, если указывать (либо не указывать) один столбец.
Если указывать несколько столбцов, то все отрабатывает отлично.

Ошибка возникает во всех версия...

**Comment by unclead** [comment]
Исправлено в ревизии 7d045ba2d304e6eabe7dc806a5719546f0bffebc
Выпустил версию 1.2.1 с фиксами после рефакоринга

p.s. Это работало в версии 1.1. Я уже создал тикет для написания тестов, чтобы такое в будущем не вылазило
