### ISSUE TITLE
Undefined index: index

### ISSUE THREAD

**Issue by phrakon** [unclead/yii2-multiple-input#281]
I updated extension and got an error
http://skrinshoter.ru/s/200319/xyw38qiQ?a

Are you sure index item will be exist? it's too brave check it here that way
https://github.com/unclead/yii2-multiple-input/blob/5e21ab734d9187c39ece3a93c9e056def741b271/src/components/BaseColumn.php#L334

**Comment by unclead** [comment]
i guess you use ListRenderer and we really didn't pass context params in this renderer. I fixed it 316521a310fecdf4265bde59e9ad84dc4406eb2f. You can update to 2.20.2

**Comment by phrakon** [comment]
thx, but

http://skrinshoter.ru/s/210319/qNW0TgE3?a

another trouble: Undefined variable: columnIndex

**Comment by unclead** [comment]
gosh! fixed in 2.20.3

**Comment by phrakon** [comment]
the same issue. third argument of renderCellContent does not exist
https://github.com/unclead/yii2-multiple-input/blob/b5d14d1c7074348d61bd1c775bfe02533863e98f/src/renderers/ListRenderer.php#L193

:)

**Comment by unclead** [comment]
if you can fix it and send PR it would be great coz as you can see i don't have enough time and make many mistakes trying to fix it quickly

**Comment by unclead** [comment]
fixed in 2.20.4 
i hope it was last bugfix)

**Comment by phrakon** [comment]
seems it's working
Stop, there is no phpdoc provided for third argument :) I'm kidding
