### ISSUE TITLE
Method 'clear' remove all rows in all multiple-input

### ISSUE THREAD

**Issue by mauztor** [unclead/yii2-multiple-input#286]
if you use multiple widgets on the page, then the method "clear" remove all rows in all multiple-input.
Solution:
in jquery.multipleInput.js on row 224:
 ` $('.js-input-remove', this).each(function () {`

**Comment by unclead** [comment]
thx for the report
fixed via 2fcdcd6d39a8c282ec29b84e7ba3c70a7e8927e7
