### ISSUE TITLE
нет кнопки добавления поля

### ISSUE THREAD

**Issue by ulrix84** [unclead/yii2-multiple-input#293]
![57b6d54d62](https://user-images.githubusercontent.com/860968/57857372-a88dbf00-77f7-11e9-8eed-3f5c90d1b469.png)
при создании вложенных инпутов, у внутреннего инпута нет кнопки добавить новый элемент, если html генерится при загрузке страницы, для добавленных на лету - все ок

**Comment by unclead** [comment]
@ulrix84 я еще не научился находишь ошибки по скриншотам 😄 Приложите код, чтобы воспроизвести проблему

**Comment by ulrix84** [comment]
@unclead, мои извинения =)
`
echo $form->field($model, 'questions')->widget(MultipleInput::className(), [
            'max' => 12,

            'allowEmptyList' => true,

            'addButtonPosition' => MultipleInput::POS_HEADER,
            'columns' => [
                [
                    'name' => 'questions',
                    'title' => 'Вопросы',
                    'value' => function ($data) {

                        return $data['name'];
                    },
                    //'type' => 'text',
                    //'items' => \yii\helpers\ArrayHelper::map($model->questions, 'id', 'name'),
                ],
                [
                    'name' => 'question_id',
                    'value' => function ($data) {

                        return $data['id'];
                    },
                    'type' => 'hiddenInput',
                ],
                [

                    'name' => 'answersArray',
                    'type' =>  MultipleInput::class,

                    'options' => [

                        'columns' => [
                            [
                                'name' => 'right',
                                'type' => MultipleInputColumn::TYPE_CHECKBOX,
                                'value' => function ($data) {
                                    // var_dump($data['name']);
                                    return $data['isRight'];
                                },
                            ],
                            [
                                'name' => 'answer_name',

                                'value' => function ($data) {
                                    // var_dump($data['name']);
                                    return $data['name'];
                                },

                            ],
                            [
                                'name' => 'answer_id',
                                'value' => function ($data) {

                                    return $data['id'];
                                },
                                'type' => 'hiddenInput',
                            ],
                        ],
                    ],
                ],
            ],

            'data' => $model->questionsArray,

            'sortable' => true,
        ])
            ->label(false);
       `

**Comment by unclead** [comment]
![image](https://user-images.githubusercontent.com/2351719/99192968-ec63da80-2786-11eb-85ee-b1f028c41eb8.png)

the issue is not reproducible at the moment, so I close it
