### ISSUE TITLE
sortable doesn't work on mobile devices

### ISSUE THREAD

**Issue by art-voloshyn** [unclead/yii2-multiple-input#300]
jquery-sortable lib from http://johnny.github.com/jquery-sortable/ what use in this project doesn't maintain for a long time and doesn't compatible with mobile devices.  How to use sortable with touch-devices?

**Comment by Slayvin** [comment]
I also noticed that the sortable doesn't really work well. I have to drag really far above the container to make it move.

**Comment by Bhoft** [comment]
> I also noticed that the sortable doesn't really work well. I have to drag really far above the container to make it move.

I have the same issue i found out that the 4th parameter (useOffset) is "undefined" when setDimensions is called.
if this is changed to true it works again. Don't know if this is related to jQuery changes or something else.


       getItemDimensions: function  () {
      if(!this.itemDimensions){
        this.items = this.$getChildren(this.el, "item").filter(
          ":not(." + this.group.options.placeholderClass + ", ." + this.group.options.draggedClass + ")"
        ).get()
        // setDimensions(this.items, this.itemDimensions = [], this.options.tolerance)
        setDimensions(this.items, this.itemDimensions = [], this.options.tolerance, true) // fixed issue with placeholder position
      }
      return this.itemDimensions
    },

**Comment by unclead** [comment]
Probably sorting is needed to be rewritten using native drag and drop API

**Comment by unclead** [comment]
the widget was migrated to sotable.js in 977ca80c115fbfc1293dbe0eb811c754f6637964 and most likely all issues caused by the usage of outdated `jquery.sortable` should have been already sorted out
