### ISSUE TITLE
multipleinput input without increment

### ISSUE THREAD

**Issue by paskuale75** [unclead/yii2-multiple-input#302]
I've multipleinput case with 2 fields : 
media_name (_'type'  => MediaManagerInputModal::className()_);
duration (_'type' => RangeInput::classname()_)

at second field, plugin add an increment value correctly, in first not .... why ?
(es. model-0-fieldName.... model-1-fieldName... etc..)
Thanks

**Comment by unclead** [comment]
best way to help maintainers to reproduce the issue is to post the example of code

**Comment by unclead** [comment]
closed due to OP inactivity
