### ISSUE TITLE
Улучшение для связанных списков

### ISSUE THREAD

**Issue by stepancher** [unclead/yii2-multiple-input#31]
Хотелось бы иметь возможность задавать что-то вроде
```
options=>[
    'items'=>function($data){
         return Object::myStaticFunctionGetItems($data->field);
    }
]
```
То есть иметь возможность задавать массив items через анонимную функцию как и value.
Очень облегчит жизнь при создании связанных списков.

**Comment by unclead** [comment]
А хочешь сделать пулл-реквест? :smile:

**Comment by stepancher** [comment]
Завтра попробую что-нибудь сделать;)

**Comment by unclead** [comment]
а что на вход принимает функция? модель? Надо подумать какие параметры могут пригодиться

**Comment by unclead** [comment]
Реализовал. Подробности в коммите 634c580e015bd8d696d3fc234da9d77bd0f15872
