### ISSUE TITLE
Can't work inner drag column inside another drag column

### ISSUE THREAD

**Issue by bscheshirwork** [unclead/yii2-multiple-input#312]
If I put nested 
```
                            'type' => MultipleInput::class,
                            'options' => [
                                'sortable' => true,
```
inside to 
```
                ])->widget(MultipleInput::class, [
                    'sortable' => true,
```
the inner drag moving to outer drop zone

**Comment by unclead** [comment]
according to the widget [documentation](http://johnny.github.io/jquery-sortable/#docs) that we use for sorting, it supports nested sorting. So we have to dig deeper and fix the issue

**Comment by bscheshirwork** [comment]
wrong selector may be?

**Comment by unclead** [comment]
I didn't investigate yet, just checked the plugin docs and found out that nested sorting is supported

**Comment by unclead** [comment]
It seems that we can rewrite sorting using native drag and drop functionality (https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API)

**Comment by unclead** [comment]
After migration to SortableJs (see 977ca80c115fbfc1293dbe0eb811c754f6637964) the issue is not reproducible anymore. I close the issue.
