### ISSUE TITLE
How to use the radio?

### ISSUE THREAD

**Issue by barsumnet** [unclead/yii2-multiple-input#315]
The mystery itself is that the widget assigns its unique names to the input radio
`<input type="radio" id="catcounterparties-phone-0-main" name="CatCounterparties[phone][0][main]" value="1" checked="" tabindex="1">
<input type="radio" id="catcounterparties-phone-1-main" name="CatCounterparties[phone][1][main]" value="1" checked="" tabindex="1">`

And because of this, the meaning of the radio button is lost.
Here is a View

    <?= $form->field($model, 'phone')->widget(MultipleInput::className(), [
                'max' => 6,
                'min' => 1, // should be at least 2 rows
                'allowEmptyList' => true,
                'enableGuessTitle' => true,
                'class' => 'form-control',
                'columns' => [
                    [
                        'title' => 'Телефон',
                        'name' => 'phone',
                        'type' => MaskedInput::className(),
                        'options' => [
                            'options' => [
                                'class' => 'form-control',
                            ],
                            'mask' => '+7(999) 999-99-99',
                            'clientOptions' => [
                                'class' => 'form-control',
                                'removeMaskOnSubmit' => true,
                            ]
                        ]
                    ],
                    [
                        'title' => 'Основной',
                        'name' => 'main',
                        'type' => 'radio',
                        'items' => [
                            true
                        ]
                    ],

                ],
                'addButtonPosition' => MultipleInput::POS_HEADER, // show add button in the header
            ])->label();
            ?>

**Comment by InsaneSkull** [comment]
All inputs of row will be copied and new index-name will be assigned. Your intend to use radio for either of row cannot be fulfilled here.

**Comment by barsumnet** [comment]
Then how to implement the plan?

**Comment by InsaneSkull** [comment]
@barsumnet Widget is not responsible for that. You can implement by yourself.

**Comment by unclead** [comment]
I think you can implement your own ColumnClass (there is the option to specify which class to use) on top of BaseColumn which will return always the same name and id for a column with radio input

our you can extend the widget logic and implement an ability to force ID/name for all rows (PR is always welcome)

**Comment by unclead** [comment]
closed due to OP inactivity
