### ISSUE TITLE
Saving multi input to related model

### ISSUE THREAD

**Issue by DenisAlliswell** [unclead/yii2-multiple-input#32]
Hi @unclead !

I have ```Gallery``` model. And I have related to it ```Videos``` model.

I need to save ```Videos``` model from  ```Gallery`` ActiveForm.

```php

class Gallery extends ActiveRecord {

public $video;

<?= $form->field($model, 'video')->widget(MultipleInput::className(), [
	'limit' => 5
]) ?>
...

public function getVideos()
{
	return $this->hasMany(Videos::className(), ['ext_id' => 'id'])->where(['ext_type'=>'gallery']);
}
...
```

```Video``` filelds to save are
```
$image_model = new Videos;
$image_model->url = $video;
$image_model->ext_type = 'youtube';
$image_model->ext_type = 'gallery';
$image_model->ext_id  = $this->id;
$image_model->save();
```

How I should save fields to ```Video``` model from ```Gallery``` model? 
In ```action``` or maybe in ```beforeSave``` method?

**Comment by unclead** [comment]
It is up to you. I prefer save related data in `afterSave` method, but it also depends on situation
Unfortunately this issue not about `yii2-multiple-input`\

p.s. i've never used widget with relation :smile:

**Comment by DenisAlliswell** [comment]
Ok, thanks anyway man! (от души :) )
