### ISSUE TITLE
ErrorException PHP7.4 - array offset on value of type null

### ISSUE THREAD

**Issue by PitBult** [unclead/yii2-multiple-input#321]
Hi! 
I have a problem. Widget not working on **PHP 7.4**.
PHP 7.3 - Everything works.

**PHP Notice – yii\base\ErrorException**
**Trying to access array offset on value of type null**

- in vendor/unclead/yii2-multiple-input/src/components/BaseColumn.php at line 249– call_user_func()
- in vendor/unclead/yii2-multiple-input/src/components/BaseColumn.php at line 320– unclead\multipleinput\components\BaseColumn::prepareValue()
- in vendor/unclead/yii2-multiple-input/src/renderers/TableRenderer.php at line 291– unclead\multipleinput\components\BaseColumn::renderInput()
- in vendor/unclead/yii2-multiple-input/src/renderers/TableRenderer.php at line 215– unclead\multipleinput\renderers\TableRenderer::renderCellContent()
- in vendor/unclead/yii2-multiple-input/src/renderers/TableRenderer.php at line 186– unclead\multipleinput\renderers\TableRenderer::renderRowContent()
- in vendor/unclead/yii2-multiple-input/src/renderers/TableRenderer.php at line 34– unclead\multipleinput\renderers\TableRenderer::renderBody()
- in vendor/unclead/yii2-multiple-input/src/renderers/BaseRenderer.php at line 378– unclead\multipleinput\renderers\TableRenderer::internalRender()
- in vendor/unclead/yii2-multiple-input/src/MultipleInput.php at line 301– unclead\multipleinput\renderers\BaseRenderer::render()

[Screenshot ErrorException](https://nimb.ws/aHgkI2)

- PHP Version | 7.4.2
- Yii Version | 2.0.32
- unclead/yii2-multiple-input | 2.22.0.0

Help me please solve this problem.

**Comment by InsaneSkull** [comment]
Did you checked your `$data` is not null? What do you have inside `$data`?

**Comment by PitBult** [comment]
This code works:
_$data['hrp_id'] ?? ''_

```php
[
    'name' => 'hrp_id',
    'type' =>  \unclead\multipleinput\MultipleInputColumn::TYPE_HIDDEN_INPUT,
    'value' => static function ($data) {
        return $data['hrp_id'] ?? '';
    },
],
```

**Comment by InsaneSkull** [comment]
@PitBult [Here is Reason](https://www.php.net/manual/de/migration74.incompatible.php#migration74.incompatible.core.non-array-access)
