### ISSUE TITLE
add or delete row without clicking  in + or x

### ISSUE THREAD

**Issue by ventarrron88** [unclead/yii2-multiple-input#323]
Hi im new usign this witget.

In general what i need to do is add or delete a row without clicking the mouse in + or X button, for example if i want to use the keyboard.  i know i can use the keyboard events but i dont know after pressing a key how to activate the event off add or delete a row.

I hope you can help me with this.  

Thanks

**Comment by unclead** [comment]
did you try to call some of the [widget's methods](https://github.com/unclead/yii2-multiple-input/wiki/Javascript-events#javascript-operations) from keypress event callback?

**Comment by ventarrron88** [comment]
Not yet, please let me check and i will tell you i solve my issue.

Thanks

**Comment by ventarrron88** [comment]
Thanks, it worked like i spected.
