### ISSUE TITLE
Not getting a value when i use kartik typeahead 

### ISSUE THREAD

**Issue by ventarrron88** [unclead/yii2-multiple-input#328]
I am using kartik's typeahead in a multiple input column, until this is everything ok, when i write a letter in this specific field it find  all the possibilities, the real problem is when i try to save In the controller  I make a foreach to get the all the values of each column for all rows but i don't know why for the columns where i use typeahead  i don't get any value, not empty, not null, nothing it just like this column does not exist.

**Comment by unclead** [comment]
@ventarrron88 at least, you have to post your code to us be able to reproduce the issue

**Comment by unclead** [comment]
closed due to OP inactivity
