### ISSUE TITLE
Change Plus Button Order

### ISSUE THREAD

**Issue by push32** [unclead/yii2-multiple-input#331]
![Screenshot-2020-07-16-at-1 39 13-PM](https://user-images.githubusercontent.com/24914270/87636228-a4965d80-c76a-11ea-898f-8899a159ed2f.png)

Hello, thanks for this great library and so helpful, now i'm in design for mobile responsive, its possible to move the plus (+) to below after add new row like the example before?

**Comment by unclead** [comment]
according to the documentation, only these options are available
```
addButtonPosition integer|array: the position(s) of add button. This can be MultipleInput::POS_HEADER, MultipleInput::POS_ROW, MultipleInput::POS_ROW_BEGIN or MultipleInput::POS_FOOTER.
```

**Comment by push32** [comment]
Yes, find it now, thank you much for the answer, Thank you so much :D

added my solution for other users also
`'addButtonPosition' => MultipleInput::POS_HEADER,`
