### ISSUE TITLE
How to load in view to update the fields

### ISSUE THREAD

**Issue by push32** [unclead/yii2-multiple-input#332]
Hello Again,

**My Model**
```
public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'profile_id' => 'Profile ID',
            'type' => 'Type',
            'value' => 'Value',
        ];
    }
```

**My Controllers**
```
foreach($model2->type as $mt){
       $model2 = new ProfileContacts();
       $model2->profile_id = $model->id;
       $model2->type = $mt['type'];
       $model2->value = strtolower($mt['value']);
       $model2->save(); 
}
```
so i save the type and value already to database, and when i'm wanna update the value using the widget, how do i load it in my controller?

**Comment by unclead** [comment]
@push32  I suggest you reading the documentation and start with this [guide](https://github.com/unclead/yii2-multiple-input/wiki/Basic-scenario-of-usage)
