### ISSUE TITLE
Uncaught TypeError: val.indexOf is not a function

### ISSUE THREAD

**Issue by push32** [unclead/yii2-multiple-input#333]
Hello, can someone help me about this issue?

`$('#multiple-input').multipleInput('add', {first: 10, second: '<option value="2" selected="selected">second</option>'});`

whats the meaning of 

> `first : 10`

because its show error 

> Uncaught TypeError: val.indexOf is not a function

and how to show 3 row of different value when init but the min is only 1?

**Comment by unclead** [comment]
@push32  did you solve the issue?

**Comment by unclead** [comment]
close due to OP inactivity
