### ISSUE TITLE
Wrong column name

### ISSUE THREAD

**Issue by panchenkodv** [unclead/yii2-multiple-input#335]
https://github.com/unclead/yii2-multiple-input/blob/627a99b5354443e4306a5645db02eab0d3b13dd5/src/MultipleInputColumn.php#L73

If renderer has one input column this code return 'true'. But if you enable 'sortable' => true, columns count become 2 and this code return 'false'. It couse wrong name for column.

**Comment by unclead** [comment]
fixed in master (b98aefd780374c7ef70addd6b4b13aa1ff5d63a3)
