### ISSUE TITLE
Make multi column in one row use ListRenderer

### ISSUE THREAD

**Issue by hadyjsc** [unclead/yii2-multiple-input#338]
Can we make or use layout in first row list renderer have 2 or more form input maybe like this.

![image](https://user-images.githubusercontent.com/16421715/100781496-b2a8fa00-343d-11eb-8f5b-5b9f5cc8ffc6.png)

the image edited use paint not in coding. if library already have layout configuration for this case, can you give me example code for implement that ? thank you.

**Comment by unclead** [comment]
@hadyjsc there is no such feature, but you can implement your own renderer with the desired behavior. Or you can add support of layout to current renderers

**Comment by hadyjsc** [comment]
@unclead oh ok, maybe next time if i have free time, i will try to explore your library and add custom layout. thanks a lot.
