### ISSUE TITLE
Вывод виджета в цикле

### ISSUE THREAD

**Issue by badtiger** [unclead/yii2-multiple-input#340]
Каким образом можно вывести виджет в цикле, для того что бы сохранить полученные данные для разных моделей.

Существует массив $model->templateExtends, у каждого элемента которого есть отношение templateExtendsVariables, при выводе в цикле, имена полей имеют одинаковое название.

```
foreach ($model->templateExtends as $templateExtend) {
    echo MultipleInput::widget([
         'model' => $templateExtend,
         'attribute' => 'templateExtendsVariables',
         'id' => 'template-extends-list-' . $templateExtend->id,
         'min' => 0,
         'max' => 50,
         'attributeOptions' => [
             'enableAjaxValidation' => true,
         ],
         'columns' => [
             [
                 'name' => 'id',
                 'type' => MultipleInputColumn::TYPE_HIDDEN_INPUT,
             ],
             [
                 'title' => Yii::t('app/template', 'Значение'),
                 'name' => 'value',
                 'enableError' => true,
             ],
         ]
    ]);
}
```

В результате, для каждого цикла $model->templateExtends я получаю поле:
```
<input type="text" id="templateextends-templateextendsvariables-0-value" class="form-control" name="TemplateExtends[templateExtendsVariables][0][value]" value="" tabindex="1">
```

Каким образом сделать, что бы добавлялся еще и id templateExtends? Что бы результат был:
```
<input type="text" id="templateextends-templateextendsvariables-0-value" class="form-control" name="TemplateExtends[1][templateExtendsVariables][0][value]" value="" tabindex="1">
```

**Comment by unclead** [comment]
я думаю нужно использовать TabularInput

**Comment by badtiger** [comment]
> я думаю нужно использовать TabularInput

Я пробовал, однако результат тот же.

**Comment by unclead** [comment]
@badtiger  у меня тоже нет готового решения с ходу. Предлагаю спросить на [форуме](https://yiiframework.ru/forum/). Там уже не раз задавали вопросы про использование виджета, может кто подскажет.
