### ISSUE TITLE
Options для input

### ISSUE THREAD

**Issue by nohnaimer** [unclead/yii2-multiple-input#346]
@unclead подскажите, как добавить настройки для input используя widget, например:
```php
                    <?= $form->field($model, 'email_aliases')->widget(MultipleInput::class, [
                        'allowEmptyList' => false,
                        'addButtonOptions' => [
                            'class' => 'btn btn-outline-success',
                        ],
                        'options' => [
                            'disabled' => true,
                        ],
                    ]) ?>
```
Например, заблокировать MultipleInput? Из InputWidget есть:
```php
/**
     * @var array the HTML attributes for the input tag.
     * @see \yii\helpers\Html::renderTagAttributes() for details on how attributes are being rendered.
     */
    public $options = [];
```
но не работает. Может это как-то делается по-другому?

**Comment by unclead** [comment]
@nohnaimer если все еще актуально, то я думаю нужно явно объявить колонку через `columns` и уже там использовать `options`
> options array|Closure: the HTML attributes for the input, you can set it as array or an anonymous function with the following signature:

**Comment by nohnaimer** [comment]
@unclead а полностью все колонки заблокировать как можно?

**Comment by unclead** [comment]
@nohnaimer никак, не было такого запроса за 5 лет :)

**Comment by nohnaimer** [comment]
@unclead понял, буду думать как кастылить…

**Comment by nohnaimer** [comment]
Хотя если поле вот такое:
```php
                    <?= $form->field($model, 'email_aliases')->widget(MultipleInput::class, [
                        'allowEmptyList' => false,
                        'addButtonOptions' => [
                            'class' => 'btn btn-outline-success',
                        ],
                    ]) ?>
```
странный костыль получается...

**Comment by unclead** [comment]
@nohnaimer а задача то какая? если хочется заблокировать поля формы из кода, то как они будут разблокироваться? наверняка будет код на js, тогда почему бы и блокировку полей не сделать через js.

**Comment by nohnaimer** [comment]
@unclead проект на yii2, есть поле в базе PostgreSQL типа array. Вот надо его показывать, но редактировать надо запретить.

**Comment by unclead** [comment]
@nohnaimer  а зачем вообще тогда использовать виджет? не проще вывести через цикл в `div`?
Ну а если нужно дать возможность редактировать, то я бы через js все разрулил (после отрисовки html установил нужным инпутам сам свойство disabled, а по нажатию на кнопку редактировать сбрасывать его). 
Не бывает супер универсальных инструментов, иногда нужно и самому код пописать 😄

**Comment by nohnaimer** [comment]
@unclead так и сделал - убрал виджет. Просто получается, что options не работает, вернее работает не для того для чего их делали - это надо бы хотя бы в phpDoc пометить 😉
