### ISSUE TITLE
Использование совместно с плагином yii2-dynamicform

### ISSUE THREAD

**Issue by Moonwolf45** [unclead/yii2-multiple-input#349]
Здравствуйте. Вообщем согласно документации yii2-dynamicform, я оформляю view таким образом:

`<?php DynamicFormWidget::begin([
                       'widgetContainer' => 'dynamicform_wrapper',
                       'widgetBody' => '.container-items',
                       'widgetItem' => '.item',
                       'limit' => 7,
                       'min' => 7,
                       'insertButton' => '.add-item',
                       'deleteButton' => '.remove-item',
                       'model' => $tickets[0],
                       'formId' => 'dynamic-form',
                       'formFields' => [
                           'status',
                           'schedule',
                       ],
                   ]); ?>

                    <div class="container-items">
                        <?php foreach ($tickets as $index => $ticket): ?>
                            <div class="item panel panel-default">
                                <div class="panel-body">
                                    <?php if (!$ticket->isNewRecord) {
                                        echo Html::activeHiddenInput($ticket, "[{$index}]id");
                                        echo Html::activeHiddenInput($ticket, "[{$index}]schedule_tickets_id");
                                    }
                                    ?>
    
                                    <?= $form->field($ticket, "[{$index}]status")->checkbox(); ?>
    
                                    <?= $form->field($ticket, "[{$index}]schedule")->widget(MultipleInput::class, [
                                        'min' => 1,
                                        'columns' => [
                                            [
                                                'name'  => 'time',
                                                'type'  => TimePicker::class,
                                                'title' => Yii::t('app', 'Time'),
                                                'defaultValue' => date('H:' . 00),
                                                'options' => [
                                                    'pluginOptions' => [
                                                        'showMeridian' => false,
                                                        'minuteStep' => 60
                                                    ]
                                                ],
                                                'nameSuffix' => $index . '_time'
                                            ],
                                            [
                                                'name' => 'time_count_tickets',
                                                'title' => Yii::t('app', 'Time count tickets'),
                                                'defaultValue' => 6,
                                                'enableError' => true,
                                                'options' => [
                                                    'type' => 'number',
                                                    'class' => 'input-priority',
                                                    'min' => 6,
                                                ],
                                                'nameSuffix' => $index . '_time_count_tickets'
                                            ],
                                            [
                                                'name' => 'price_adults',
                                                'type'  => NumberControl::class,
                                                'title' => Yii::t('app', 'Price adults'),
                                                'defaultValue' => 1,
                                                'enableError' => true,
                                                'options' => [
                                                    'class' => 'input-priority',
                                                ],
                                                'nameSuffix' => $index . '_price_adults'
                                            ],
                                            [
                                                'name' => 'price_stud',
                                                'type'  => NumberControl::class,
                                                'title' => Yii::t('app', 'Price stud'),
                                                'defaultValue' => 1,
                                                'enableError' => true,
                                                'options' => [
                                                    'class' => 'input-priority',
                                                ],
                                                'nameSuffix' => $index . '_price_stud'
                                            ],
                                            [
                                                'name' => 'price_children',
                                                'type'  => NumberControl::class,
                                                'title' => Yii::t('app', 'Price children'),
                                                'defaultValue' => 1,
                                                'enableError' => true,
                                                'options' => [
                                                    'class' => 'input-priority',
                                                ],
                                                'nameSuffix' => $index . '_price_children'
                                            ],
                                        ]
                                    ])->label(Yii::t('app', 'Schedule') . ' (' . Yii::$app->formatter->asDate($dates[$index]) . ')'); ?>
                                </div>
                            </div>
                        <?php endforeach; ?>
                    </div>
                <?php DynamicFormWidget::end(); ?>`
                
Но в этом слачае ваш плагин не видит уже имеющиеся данные, и не сохраняет их при ошибки валидации, однако если убрать index, то все начинает работать, однако тогда данные уже нельзя будет обновить потому, что они не приходят, их просто нет. Как это можно пофиксить?

**Comment by Moonwolf45** [comment]
Всё заставил работать, пришлось добавить одну дополнительную строку:
`<?= $form->field($ticket, "[{$index}]schedule")->widget(MultipleInput::class, [
                                        'min' => 1,
                                        'value' => $ticket->schedule,
                                        'columns' => [
                                         ...
                                         ]); ?>`

**Comment by unclead** [comment]
Раз вопрос решен, то я закрываю issue
