### ISSUE TITLE
bug in multipleInput.js

### ISSUE THREAD

**Issue by andrtechno** [unclead/yii2-multiple-input#350]
https://github.com/unclead/yii2-multiple-input/blob/fa4a69a96643b532ea2b49f86bdd6aeb6cd201a7/src/assets/src/js/jquery.multipleInput.js#L345

при  сортировки. не верно работает добавление
если после сортировки мы имеет такой вид

row input 1 [index=2]
row input 2 [index=0]
row input 3 [index=1]

то после добавление, мы получаем такой вид
row input(new) [index=2]
row input 1 [index=2]
row input 2 [index=0]
row input 3 [index=1]
т.е дубликат индексов

как это исправить
jquery.multipleInput.js addInput()
https://github.com/unclead/yii2-multiple-input/blob/master/src/assets/src/js/jquery.multipleInput.js#L345
` $wrapper.data('multipleInput').currentIndex++; `
передвинуть по выше. например сюда
https://github.com/unclead/yii2-multiple-input/blob/master/src/assets/src/js/jquery.multipleInput.js#L273

**Comment by unclead** [comment]
@andrtechno  не получается воспроизвести. Есть пример кода? еще можно сделать скриншот из chrome dev tool, чтобы было видно что индексы реально кривые.

**Comment by andrtechno** [comment]
@unclead 
```
echo $form->field($model, 'test')->widget(\unclead\multipleinput\MultipleInput::className(), [
    'max' => 6,
    'min' => 2, // should be at least 2 rows
    'allowEmptyList' => true,
    'sortable'=>true,
    'prepend'=>true,
    'rendererClass' => \unclead\multipleinput\renderers\TableRenderer::class,
    'addButtonPosition' => \unclead\multipleinput\MultipleInput::POS_HEADER, // show add button in the header
])->label(false);
```

Добавляем несколько Row и сортируем их, сохраняем запись в базу

После сохранение записи нажимаем "добавить row" и видим дубль индекса

**Comment by andrtechno** [comment]
![Screenshot_8](https://user-images.githubusercontent.com/6948026/127457510-6b993b79-9a05-4a17-a523-03429dffb258.jpg)
![Screenshot_9](https://user-images.githubusercontent.com/6948026/127457525-6c8906a0-98cb-4262-a6ad-26d01fe6eae0.jpg)

**Comment by andrtechno** [comment]
ps иконки у меня просто не подключены, по этому не отображаются

**Comment by unclead** [comment]
Воооот! То есть нужно сохранить в базу сначала и это уже выглядит как reproduce case 😄  Подебажу на днях

**Comment by unclead** [comment]
@andrtechno в общем сделал фикс в 2.26.0. Вообще похожая проблема уже всплывала раньше и ее можно было обойти на стороне сервера, если перед сохранение сделать array_values, чтобы сбросить индексы массива.

_p.s. Конечно текущая архитектура уже начинает трещать по швам и уже давно нужно все рефакторить 😄_

**Comment by andrtechno** [comment]
все равно бага присутствует, если не брать во внимание сортировку, то после добавление нового ROW индексы не правильные
если сделать так, то норм
```
    var findMaxRowIndex = function($wrapper) {
        return findRows($wrapper).length - 1;
    };
```
