### ISSUE TITLE
Проблема с клонированием

### ISSUE THREAD

**Issue by Moonwolf45** [unclead/yii2-multiple-input#351]
Здравствйте. Вообщем, использую ваш плагин совместно, динамической формой "wbraganca/yii2-dynamicform" (это для справки) и вообщем когда при нажатии кнопки скопировать строку, он её копирует, но все данные сдвигаются вправо на один стобец, вот как это выглядит:
![1](https://user-images.githubusercontent.com/32763691/127816993-60adb95c-478c-4a21-946e-133593ed2c84.JPG)

Ну вообщем как это можно решить, вот код формы:
`                       <div class="item panel panel-default">
                                <div class="panel-body">
                                  
                                    <?= $form->field($ticket, "[{$index}]status")->checkbox(); ?>

                                    <?= $form->field($ticket, "[{$index}]schedule")->widget(MultipleInput::class, [
                                        'min' => 1,
                                        'value' => $ticket->schedule,
                                        'cloneButton' => true,
                                        'columns' => [
                                            [
                                                'name'  => 'time',
                                                'type'  => TimePicker::class,
                                                'title' => Yii::t('app', 'Time'),
                                                'defaultValue' => date('H:' . 00),
                                                'options' => [
                                                    'pluginOptions' => [
                                                        'showMeridian' => false,
                                                        'minuteStep' => 60
                                                    ]
                                                ],
                                            ], [
                                                'name' => 'time_count_tickets',
                                                'title' => Yii::t('app', 'Time count tickets'),
                                                'defaultValue' => 6,
                                                'enableError' => true,
                                                'options' => [
                                                    'type' => 'number',
                                                    'class' => 'input-priority',
                                                    'min' => 6
                                                ]
                                            ], [
                                                'name' => 'price_adults',
                                                'type'  => NumberControl::class,
                                                'title' => Yii::t('app', 'Price adults'),
                                                'defaultValue' => 1,
                                                'enableError' => true,
                                                'options' => [
                                                    'class' => 'input-priority'
                                                ]
                                            ], [
                                                'name' => 'price_stud',
                                                'type'  => NumberControl::class,
                                                'title' => Yii::t('app', 'Price stud'),
                                                'defaultValue' => 1,
                                                'enableError' => true,
                                                'options' => [
                                                    'class' => 'input-priority'
                                                ]
                                            ], [
                                                'name' => 'price_children',
                                                'type'  => NumberControl::class,
                                                'title' => Yii::t('app', 'Price children'),
                                                'defaultValue' => 1,
                                                'enableError' => true,
                                                'options' => [
                                                    'class' => 'input-priority'
                                                ]
                                            ]
                                        ]
                                    ])->label(Yii::t('app', 'Schedule') . ' (' . Yii::$app->formatter->asDate($dates[$index]) . ')'); ?>
                                </div>
                            </div>`

Вот основная часть, думаю остальной код будет лишним, хотя могу добавить и его, если необходимо

**Comment by Moonwolf45** [comment]
Еще может быть вот так, если нажимать уже на скопированные строки:
![2](https://user-images.githubusercontent.com/32763691/127818994-617ad2b5-3f57-4323-9a99-9c368553c3b0.JPG)

**Comment by unclead** [comment]
will be fixed in #348 (I close this ticket as duplicat)

**Comment by unclead** [comment]
@Moonwolf45 The issue Should be fixed in the version 2.25.0
