### ISSUE TITLE
duplicate keys causing strange behavior

### ISSUE THREAD

**Issue by RodrigoDornelles** [unclead/yii2-multiple-input#358]
this happens when I go to edit, when I add a new input it is not getting the last key correctly, which causes several problems.

| ![screen1](https://user-images.githubusercontent.com/29123479/131853899-47162d8c-8dcc-4efc-84d8-7050ffe2b80c.png) | ![screen2](https://user-images.githubusercontent.com/29123479/131853908-f7ad58fd-22c7-4e18-804d-da0e05ef3bff.png) |
| - | - |

**Comment by unclead** [comment]
do you use the latest version (2.26.0)? because it's probably has been fixed in becc3dd576ae0533ded89d3d30b28201286ea7b0

**Comment by RodrigoDornelles** [comment]
that's right, now it's working with a more updated version.
