### ISSUE TITLE
wrong version hardcoded in composer.json

### ISSUE THREAD

**Issue by cebe** [unclead/yii2-multiple-input#361]
Your package has tagged as version 2.26.0 on github, but we can't install that version via composer because version 2.24.0 is hardcoded in composer.json:

https://github.com/unclead/yii2-multiple-input/blob/651f07c875494bba82cf6e1589ed43fff1fdb267/composer.json#L12

is there a reason to have the version in composer.json? if not, please remove it and tag a fresh release that does not have this issue.

**Comment by unclead** [comment]
@cebe  thx for pointing the issue. Of course, it was just a type. Frankly, didn't know that `version` is optional 😄 

fixed in 2.26.1
