### ISSUE TITLE
render addons in text fields

### ISSUE THREAD

**Issue by ritacionfoli** [unclead/yii2-multiple-input#364]
Hi, I'd like to know if is possible to append/prepend an addon to a text input like this

![addon](https://user-images.githubusercontent.com/9607089/136584451-8953dc51-a105-4651-bdbb-3e61e486592c.png)

**Comment by unclead** [comment]
@ritacionfoli It turned out the widget provides such a feature, but it wasn't documented 😞 
I added it to the docs and here it is
```
inputTemplate string the template of input for customize view. Defailt is {input}.

Example

<div class="input-group"><span class="input-group-addon"><i class="fas fa-mobile-alt"></i></span>{input}</div>

```

[documentation](https://unclead.github.io/yii2-multiple-input/configuration/#column-options)
