### ISSUE TITLE
all icon missing

### ISSUE THREAD

**Issue by kenjisoul** [unclead/yii2-multiple-input#366]
This is my code after install

```
 <?=
            $form->field($model, 'i_name')->widget(MultipleInput::className(), [
                'max' => 6,
                'min' => 1, // should be at least 2 rows
                'allowEmptyList' => false,
                'enableGuessTitle' => true,
                'addButtonPosition' => MultipleInput::POS_HEADER, // show add button in the header
            ])
            ->label(false)
 ?>
```

![image](https://user-images.githubusercontent.com/5521214/140754509-ff3f5543-0b21-49d4-a150-b211fac6aee6.png)

**Comment by unclead** [comment]
@kenjisoul what version of the widget you're using?

**Comment by kenjisoul** [comment]
"unclead/yii2-multiple-input": "~2.0"

yii2 latest version

bootstrap4

**Comment by kenjisoul** [comment]
> @kenjisoul what version of the widget you're using?

"unclead/yii2-multiple-input": "~2.0"

yii2 latest version

bootstrap4

**Comment by unclead** [comment]
the widget was written in the time of BS3 and nobody has added support of BS4 😄 Probably, you need to use this trick https://unclead.github.io/yii2-multiple-input/icons/

**Comment by unclead** [comment]
@kenjisoul did it solve the issue?

**Comment by kenjisoul** [comment]
@unclead I cannot find icon library to add that code, which file to add that code?

**Comment by unclead** [comment]
It depends on the icon library you're using. AFAIR, there is no built-in library like `glyphicons` in BS4, so you should:
1) either use `font awesome` and in in this case you just need to set the option iconSource in the widget settings
```
<?=
            $form->field($model, 'i_name')->widget(MultipleInput::className(), [
                'max' => 6,
                'min' => 1, // should be at least 2 rows
                'allowEmptyList' => false,
                'enableGuessTitle' => true,
                'addButtonPosition' => MultipleInput::POS_HEADER, // show add button in the header
               'iconSource' => 'fa'
            ])
            ->label(false)
 ?>

2) or you a custom library and configure required icons using the option 'iconMap'

**Comment by kenjisoul** [comment]
I'm solved.

add this link `<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css" rel="stylesheet">` and add `'iconSource' => 'fa'`
