### ISSUE TITLE
Add support of clientValidation

### ISSUE THREAD

**Issue by duynguyen0511** [unclead/yii2-multiple-input#37]
cant figure out why yii2-multiple-input client validation does not work ? Is it not a built-in feature ?

**Comment by unclead** [comment]
Currently only ajaxValidation works because widget uses Html helper for rendering inputs. ClientValidation works when you use ActiveField for rendering. We can extend widgets's logic for this case but it will works only when you work with AR model.

**Comment by duynguyen0511** [comment]
okay, I am using Tabular Input ( https://github.com/unclead/yii2-multiple-input/blob/master/docs/tabular_input.md) . I hope it is possible to do client-validation. 

Great works on the plugin. 

Thanks

**Comment by unclead** [comment]
I think i we can add new property `enableActiveFieldRendering` or something similar with `false` value by default for BC. If this property is true widget will use `$form->field` for rendering inputs. I'm not sure about name of property and i need your opinion.

**Comment by duynguyen0511** [comment]
Hi unclead, 

can we check for "enableClientValidation" value instead of introducing new property ?

**Comment by unclead** [comment]
Yes, I think we can use enableClientValidation from ActiveForm. Unfortanetly i dont have free time to implement this feature now, too busy on main work

**Comment by duynguyen0511** [comment]
no problem man, no rush. I understand.

**Comment by unclead** [comment]
Closed via d08fe29e1483d81bd78deb7c03f3be346410a4ff

**Comment by unclead** [comment]
After performing some test i realized that current implementation does not cover all cases and also current functionality is broken. I moved the feature to the new branch and reverted the master branch to a stable state

**Comment by unclead** [comment]
resolved via 156e38f93b94b77722e2f2a0b1c53f17df1232e5
