### ISSUE TITLE
Иногда не обновляется currentIndex после добавления первой строки

### ISSUE THREAD

**Issue by semivori** [unclead/yii2-multiple-input#375]
Файл jquery.multipleInput.js
![image](https://user-images.githubusercontent.com/37557958/230130662-7048bb7e-e908-4a50-9a80-f97eb3d639da.png)

Мой обработчик события afterAddRow
![image](https://user-images.githubusercontent.com/37557958/230131071-b1350017-0ab7-4246-a776-2cdbf6dfb1ee.png)

Кликом на add кнопку добавляю две строки, имеем такое в консоли
![image](https://user-images.githubusercontent.com/37557958/230131347-6bff41e5-bfb0-4a71-b065-bc30cd788485.png)

Соответственно имена инпутов так же имеют одинаковые индексы.

Повторюсь, баг всплывает не всегда и вроде бы только на первых двух строках.
версия виджета 2.27.0

**Comment by semivori** [comment]
я нашел причину, если автору виджета интересно могу обьяснить

**Comment by unclead** [comment]
@semivori сделаешь PR?

**Comment by semivori** [comment]
> @semivori сделаешь PR?

@unclead та я просто сделал костыль для себя. Я делаю неактивной кнопку добавления, пока не словлю событие afterInit. А сама причина в том, что пользователь может добавить несколько строк пока отработает этот колбек https://i.imgur.com/4RS8hIu.png и currentIndex слетит в ноль. 

А для чего ты поместил этот код в интервал, без этого никак?

**Comment by semivori** [comment]
@unclead я разобрался, бага нет.
