### ISSUE TITLE
Add new row should not copy values of the most recent row

### ISSUE THREAD

**Issue by duynguyen0511** [unclead/yii2-multiple-input#39]
On create, it works fine. When you click "+" to add new row, it gives you all blank value even though you may fill in values for your first row. 

On update, when you click "+" to add new row, the new row will get the value of the closest row. 
![update](https://cloud.githubusercontent.com/assets/436950/10143016/329a74e4-65d3-11e5-9d96-0d72efae9fd7.png)
![create](https://cloud.githubusercontent.com/assets/436950/10143017/329ad0b0-65d3-11e5-97fc-23c5c55a365c.png)

The reason for that is I will have "id" field hidden on update, so when I update existing value, I check for "id" in the database and update new values (not going to delete all and re-create all because other table will use the "id" as foreign key)

**Comment by unclead** [comment]
Want to try to fix it? 
Or give me the example of code with action and model to reproduce it.

**Comment by duynguyen0511** [comment]
Hi unclead, 

Here is all the controllers and view file. (https://gist.github.com/duynguyen0511/22360b8b70be204521f0)

1 Work Order can have Many Tasks

![update](https://cloud.githubusercontent.com/assets/436950/10170531/854b2c14-6692-11e5-9035-b2a2b87a6e61.png)

**Comment by unclead** [comment]
Fixed via 09f37624cdcd2bb2e036d4c8f67c6218db0f3984

**Comment by duynguyen0511** [comment]
@unclead thanks

Love to have author actively involved in his project :)
