### ISSUE TITLE
Improve documentation on validating

### ISSUE THREAD

**Issue by bethrezen** [unclead/yii2-multiple-input#41]
In docs/multiple_input_single.md there's an example of validating through separate function with foreach loop.
The same can be done with [each validator](http://www.yiiframework.com/doc-2.0/guide-tutorial-core-validators.html#each) that is available since yii 2.0.4:
```php
[['email'], 'each', 'rule'=>['email']],
```

**Comment by unclead** [comment]
I tried the validator and unfortunately it is not suitable because it returns that field `emails` has error instead of return which elements are incorrect.

Errors with EachValidator
```
examplemodel-emails: ["Emails is not a valid email address."]
```

but widget expects
```
examplemodel-emails-3: ["the input value is not a valid email address."]
```

If i use `EachValidator` wrong way please give me the correct example
