### ISSUE TITLE
jQuery issues

### ISSUE THREAD

**Issue by createspy** [unclead/yii2-multiple-input#42]
I've spent for couple hours trying to get extension work, but could not.

Firstly, you can't use data() like this:

```javascript
            $wrapper.data('multipleInput', {
                settings: settings,
                currentIndex: 0,
                attributeDefaults: {}
            });
```

It just doesn't work. The explonation is here: http://stackoverflow.com/questions/6827810/unable-to-set-data-attribute-using-jquery-data-api

Next, where did you get such events?

```javascript
      $(document).on('click.multipleInput', ....);
```

I was trying to fix it, but it was like a snowball, and all that I got was just a single text input without able to add fields.

**Comment by unclead** [comment]
I dont want to update the DOM via `data` method, i am using it like a storage. I think if `data` method didnt work it would not have been used in yiiActiveForm.js. 
Look at: https://github.com/yiisoft/yii2/blob/master/framework/assets/yii.activeForm.js#L200

>  
```
$(document).on('click.multipleInput', ....);
```

It is just namespace for event: https://api.jquery.com/event.namespace/
I cant understand what is the problem with it?

**Comment by unclead** [comment]
what version of jquery are you using?

**Comment by createspy** [comment]
I'm sorry, I have solved this issue. It was my miss, connected with resolving asset bundles. Now, all seems ok, thank You.
