### ISSUE TITLE
bad pattern on regexp

### ISSUE THREAD

**Issue by lorinczelod** [unclead/yii2-multiple-input#43]
In
unclead/widgets/renderers/TableRenderer.php, line 141
instead of:
```
$cells[0] = preg_replace('/^(<td[^>]+>)(.*)(<\/td>)$/', '${1}' . $hiddenInputs . '$2$3', $cells[0]);
```
we need this (with s (PCRE_DOTALL) modifier):
```
$cells[0] = preg_replace('/^(<td[^>]+>)(.*)(<\/td>)$/s', '${1}' . $hiddenInputs . '$2$3', $cells[0]);
```
for multiline search inside of 'td' tag.
Do you agree?

**Comment by unclead** [comment]
This fix already in master. Look at 11763d14ce70e1170c9d94f6ec88513bff890d85
