### ISSUE TITLE
Dependent Dropdown

### ISSUE THREAD

**Issue by rahulk-k** [unclead/yii2-multiple-input#44]
I want to use dependent dropdown. how is it possible ?

**Comment by unclead** [comment]
I need to try. Never tried it before :smile:

**Comment by unclead** [comment]
@rahulk-k have you tried this widget: https://github.com/kartik-v/yii2-widget-depdrop

You can use this widget in the same way as other widgets. Cant see any problems with it

**Comment by YasserSB** [comment]
If we use this widget: https://github.com/kartik-v/yii2-widget-depdrop

when reguler use with https://github.com/kartik-v/yii2-widget-depdrop , i dont have issue, but when combine it with multiple input how we set the parent target of depdrop? can you give me example?
i am little confuse with it.

**Comment by unclead** [comment]
@YasserSB i guess this https://github.com/unclead/yii2-multiple-input/wiki/Tips-and-Tricks#use-of-a-widgets-placeholder can helps you

**Comment by YasserSB** [comment]
Oh I miss it, thank you so much :D

I think this close my issue ;)

**Comment by loveorigami** [comment]
I have same question
My config
```php
<?= $form->field($model, 'field')->widget(MultipleInput::className(), [
                            'id' => 'my_id',
                            'max' => 2,
                            'rowOptions' => [
                                'id' => 'row{multiple_index_my_id}',
                            ],
                            'columns' => [
                                [
                                    'name' => 'parent_ids',
                                    'type' => 'dropDownList',
                                    'items' => $this->getCats(),
                                    'options' => [
                                        'id' => 'parent-{multiple_index_my_id}'
                                    ]
                                ],
                                [
                                    'name' => 'child_ids',
                                    'type' => \kartik\depdrop\DepDrop::class,
                                    'options' => [
                                        'pluginOptions' => [
                                            'depends' => ['parent-{multiple_index_my_id}'],
                                            'placeholder' => 'Select...',
                                            'url' => 'wqw'
                                        ]
                                    ]
                                ],
                            ]
    ]);
    ?>
```

but in 'depends' => ['parent-{multiple_index_my_id}'], placeholder is not replaced.

**Comment by ered15** [comment]
@loveorigami did u find a solution for that problem? im having the same issue

**Comment by loveorigami** [comment]
@ered15 No, I did without kartik\depdrop\DepDrop

**Comment by ered15** [comment]
well that's bad news, I have everything working as expected, just missing the dynamic ID, I tried using  depdrop_all_params putting manual ids using an array 

> 'depends'=>[0='parent-0',1=>'parent-1']

but it's not working as expected when adding rows, @unclead any tip to get this working?
