### ISSUE TITLE
urlencoded field token

### ISSUE THREAD

**Issue by rolmonk** [unclead/yii2-multiple-input#49]
[yii2-elfinder](https://github.com/MihailDev/yii2-elfinder) extension is using urlencoded field token - `%7Bmultiple-index%7D`, which is not replaced in jsTemplate, and then doesn't work correctly.

As a temporary solution I changed line 149 of jquery.multipleInput.js from
`jsTemplate = settings.jsTemplates[i].replaceAll('{multiple-index}', data.currentIndex);` 
to
`jsTemplate = settings.jsTemplates[i]
.replaceAll('{multiple-index}', data.currentIndex)
.replaceAll('%7Bmultiple-index%7D', data.currentIndex);`

**Comment by unclead** [comment]
I think you solution is ok. Can you make a PR based on last revision? In last revision there is no plecaholder `multiple-index`, widget uses placeholder `multiple_index` now
