### ISSUE TITLE
MultipleInput allowEmptyList

### ISSUE THREAD

**Issue by webspec2012** [unclead/yii2-multiple-input#52]
When using allowEmptyList there is one empty line for record addition.
I want that initially there were no lines, and appeared only when pressing the button to add.

**Comment by webspec2012** [comment]
Почитал закрытые issue, оказывается можно писать на русском =)
Так проще.

Опишу свою ситуацию, у меня есть поля ввода телефонов.

Организовано примерно так:

```
<?= $form->field($model, 'phones')->widget(MultipleInput::className(), [
        'limit' => 5,
        'allowEmptyList' => true,
        'columns' => [
            // тип телефона
            [
                'name' => 'type',
                'title' => 'Тип',
                'type'  => 'dropDownList',
                'defaultValue' => 'phone',
                'items' => Phone::getTypeList()
            ],

            // префикс
            [
                'name' => 'prefix',
                'title' => 'Префикс',
            ],

            // телефон с маской
            [
                'name' => 'value',
                'title' => 'Номер телефона',
                'type' => MaskedInput::className(),
                'options' => [
                    'class' => 'input-phone',
                    'mask' => [
                        '+7(999) 999-99-99',
                    ]
                ]
            ],

            // постфикс
            [
                'name' => 'postfix',
                'title' => 'Постфикс',
            ],
        ],
    ]);?>
```

На стороне сервера значения ловятся как массив моделей Phone, к каждой из которой применяется валидация. Так вот, изначально при открытии формы, MultipleInput добавляет пустую строку для добавления, и получается, что если пользователь открыл форму, но ничего не заполнил, то получает ошибку валидации телефона. Хотелось бы, что бы была возможность не создавать эту пустую строку. Если пользователь захочет, он сам нажмет на кнопку добавления и добавит телефон.

**Comment by unclead** [comment]
Relates with #48

**Comment by unclead** [comment]
Добавил опцию `min`. Если задать ее как 0, то первой строки не будет.
Подробнее в README либо в коммите f351bbc531f6f295818831a5d4f6337c5eea323c
