### ISSUE TITLE
Отсутствует поле в POST запросе при пустом списке.

### ISSUE THREAD

**Issue by webspec2012** [unclead/yii2-multiple-input#54]
Никак не пойму.

Добавляю несколько записей, всё ок. удаляю одну, всё ок.
но если удаляю все записи, то при сохранении в POST запросе данное поле вообще нет, поэтому модель считает, что его сохранять ненадо, и в итоге последняя запись так и остается.

подскажите пожалуйста, где я накосячил?

**Comment by unclead** [comment]
надо подумать, я не встречался с таким примером использования.

**Comment by webspec2012** [comment]
В качестве временного решения, в форме добавляю перед виджетом hidden поле, тогда если сам виджет ничего не передаст, это поле передаст пустое значение.

```
<?= $form->field($model, 'phones')->hiddenInput(['id' => 'phones-fake', 'value' => ''])->label(false);?>
```

**Comment by unclead** [comment]
На мой взгляд решение данной проблемы лежит за рамками гранци отвественности виджета. Цель виджета - отрисовать форму добавления значений, а как они будут обрабатываться на стороне сервера его не должно беспокоить.

Можно добавить конечно hidden поле, но это выглядит как решение конкретной задачи, а не нечто общее
