### ISSUE TITLE
Add rowOptions parameter

### ISSUE THREAD

**Issue by unclead** [unclead/yii2-multiple-input#56]
I am using the yii2-multiple-input extension
and I want define more than one class to row on tabularInput,

for example:
this class: multiple-input-list__item
I want change to: "multiple-input-list__item and phone-number" 2 classes for one row
and in another to: "multiple-input-list__item and address"

How may I add this ?

thanks man!

(sorry my bad english)

**Comment by unclead** [comment]
closed via 5b4d1c21c2f514f7a946c71dfb12d7c2d5dbaab3

**Comment by arthurfsilva** [comment]
Thank you man! XD
