### ISSUE TITLE
Add columnClass paramter

### ISSUE THREAD

**Issue by ZAYEC77** [unclead/yii2-multiple-input#59]
@unclead Hello, I think it's good idea to add `columnClass`parameter to `MultipleInput`.
What do You think about it?

**Comment by unclead** [comment]
@ZAYEC77 you're right it can be usefull. Can you prepare a PR?

**Comment by unclead** [comment]
Closed via dbe6670cfbe889b66d9368fd4fcd56fc5aea6931

**Comment by ZAYEC77** [comment]
@unclead Thanks)
