### ISSUE TITLE
Incorrect display of buttons when using both 'min' and 'limit'

### ISSUE THREAD

**Issue by artur-ciesielski** [unclead/yii2-multiple-input#63]
I have two emails, with limit = 2 and min = 1. When I render the form, there is no red X button next to the second input. When I set the limit to 3 there is no button next to 3rd input.

Generally it looks like the last input doesn't have it's button correctly generated - inspector shows an empty <td> block.

**Comment by unclead** [comment]
which version do you use? probably it was fixed via 34efb860cdd13f8eb6a1b5d8e6aa2a7dc3938325

also it can be useful if you show me the example of code to reproduce this bug

**Comment by artur-ciesielski** [comment]
Ok, thank you. Composer didn't pull the latest version until I specifically told him to. It's working now, I am closing this issue.
