### ISSUE TITLE
Not able to save value via post.

### ISSUE THREAD

**Issue by macrawat** [unclead/yii2-multiple-input#66]
Hi unclead !!

yii2-multiple-input is a very much required plugin for my projects where i have multiple row values assigned to single row. How ever i am not able to save the multiple row values as i am not getting them into to my controller action via post method. Can you please provide the working test cases along with MVC. 
Thanks !! Great work !!

**Comment by unclead** [comment]
What about this https://github.com/unclead/yii2-multiple-input/tree/master/examples ?
Or you cannot understand how to save data into DB and then retrieve it?

**Comment by unclead** [comment]
closed because topic starter is inactive
