### ISSUE TITLE
{multiple_index} at row #1

### ISSUE THREAD

**Issue by zozo904** [unclead/yii2-multiple-input#70]
{multiple_index} at row #1 return {multiple_index}
{multiple_index} at row #2 return 2
{multiple_index} at row #3 return 3

e t c

На первой строке виджета данная переменная возвращает саму себя при рендере в js.
Насколько я понимаю она должна возвращать 0.

**Comment by unclead** [comment]
Как воспроизвести? Это на базовом примере?

Вообще {multiple_index} возвращается для использования в шаблоне в js.

При рендеринге уже существующих данных плейсхолдеры заменяются на соотвествующие значения

**Comment by unclead** [comment]
![wzipgsr](https://cloud.githubusercontent.com/assets/2351719/14289423/8638bf90-fb7c-11e5-99aa-ecc995aa435d.png)

**Comment by zozo904** [comment]
Пытался добавить Dep DropDown из двух полей. 
На первом висел js на onchange с {multiple_index} для того чтобы он отрабатывал изменение первого и загонял данные во второй dropdown. 
Во второй и последующих группах все проходит нормально. В первом вместо индекса 0 остается так же {multiple_index} в скрипте. Разбираться времени не было.
Воспроизвести заново смогу только по наличии времени. Сейчас некогда. Заменил пока другим расширением wbraganca\dynamicform\DynamicFormWidget.

**Comment by zozo904** [comment]
Пытался добавить Dep DropDown из двух полей. 
На первом висел js на onchange с {multiple_index} для того чтобы он отрабатывал изменение первого и загонял данные во второй dropdown. 
Во второй и последующих группах все проходит нормально. В первом вместо индекса 0 остается так же {multiple_index} в скрипте. Разбираться времени не было.
Воспроизвести заново смогу только по наличии времени. Сейчас некогда. Заменил пока другим расширением wbraganca\dynamicform\DynamicFormWidget. 

Вот код нашел в бекапах
`     <?= $form->field($model, 'fff')
			->widget(MultipleInput::className(), [
				//'limit' => 4,
				'allowEmptyList'    => false,
				'rowOptions' => 
				[
					'id' => 'tsrrow{multiple_index}',
				],
				'columns' => [
					[
						'name'  => 'cat',
						'type'  => 'dropDownList',
						'title' => 'Категория',
						'defaultValue' => '0',
						'items' => $items,
						'options'=>
							[
								'onchange'=>
									'$.post("index.php?r=fffa/list&id='.'"+$(this).val(),
										function(data){
											console.log($("#fffa-form").yiiActiveForm);
											if(isFinite(\'{multiple_index}\'))
												{
													$("select#fffa-tsr-{multiple_index}-subcat").html(data); 
												}
											else
												{
													$("select#fffa-tsr-0-subcat").html(data); 
												}
											
										} );
									',
							],
					],
					[
						'name'  => 'subcat',
						'type'  => 'dropDownList',
						'title' => 'Под-Категория',
						'items' => $subitems,
						'options'=>
						['id' => 'tsr-{multiple_index}-subcat',],
					],
					[
						'name'  => 'tsrkol',
						//'type' => \yii\widgets\MaskedInput::classname(),
						'title' => 'Количество по ИПР',
						//'options' => ['mask' => '[9]{4}'],
						'headerOptions' => [
							'style' => 'width: 100px;',
						]
					],
					[
						'name'  => 'tsryear',
						//'type' => \yii\widgets\MaskedInput::classname(),
						'title' => 'Количество в год',
						'enableError' => true,
						//'options' => ['mask' => '[9]{4}'],
						'headerOptions' => [
							'style' => 'width: 100px;',
						]
					],
					[
						'name'  => 'tsrcomment',
						'title' => 'Комментарий к ТСР',
						'enableError' => true,
					],			
/*					
					[
						'name'  => 'day',
						'type'  => \kartik\date\DatePicker::className(),
						'title' => 'Day',
						'value' => function($data) {
							return $data['day'];
						},
						'items' => [
							'0' => 'Saturday',
							'1' => 'Monday'
						],
						'options' => [
							'pluginOptions' => [
								'format' => 'dd.mm.yyyy',
								'todayHighlight' => true
							]
						],
						'headerOptions' => [
							'style' => 'width: 250px;',
							'class' => 'day-css-class'
						]
					],
					[
						'name'  => 'priority',
						'enableError' => true,
						'title' => 'Priority',
						'options' => [
							'class' => 'input-priority'
						]
					],
					[
						'name'  => 'comment',
						'type'  => 'static',
						'value' => function($data) {
							return Html::tag('span', 'static content', ['class' => 'label label-info']);
						},
						'headerOptions' => [
							'style' => 'width: 70px;',
						]
					]
					*/
				]
			 ])
	
	
	?>`

**Comment by unclead** [comment]
Спасибо за инфу, попробую воспроизвести на данном примере т.к. сам с таким кейсом не сталкивался.

**Comment by unclead** [comment]
Fixed via 24158de26db20611f7280d02670740fd35671824
