### ISSUE TITLE
The name of the attribute is appearing twice in the input name

### ISSUE THREAD

**Issue by unclead** [unclead/yii2-multiple-input#73]
Hello,

First of all I must commend you on this very useful plugin. Thank you!

If you have a moment, I have a strange issue that I cannot solve despite reviewing my code and your instructions many times over.

The short description:
The name of the attribute is appearing twice in the input name. Like this:
<input type="text" id="sitesetting-sb_email_recipient_list-sb_email_recipient_list-0" class="form-control" name="SiteSetting[sb_email_recipient_list][sb_email_recipient_list][0]" value="">

The details:
I am using the latest version of your code (updated yesterday)
I have an instance of a class named SiteSetting which inherits \yii\mongodb\ActiveRecord ($model) and has an attribute named sb_email_recipient_list.
I am outputting the field in the following manner:
$form = new \yii\widgets\ActiveForm([....]);
echo $form->field($model, 'sb_email_recipient_list')->widget(MultipleInput::classname(), [ /* empty array */ ])

Do you have any idea what could be causing this?

Much thanks in advance,
Chaim

**Comment by chaiml** [comment]
**Clarification**
The errant HTML input looks like this:
`<input type="text" id="sitesetting-sb_email_recipient_list-sb_email_recipient_list-0" class="form-control" name="SiteSetting[sb_email_recipient_list][sb_email_recipient_list][0]" value="">`

**Comment by unclead** [comment]
Fixed via a85e1f2711422323367f1a8aafafa58a31ac9819

You can use develop branch to get the changes, i will release new version soon

**Comment by chaiml** [comment]
Confirmed that this solves the problem. Thank you!
