### ISSUE TITLE
Use plugin in modal

### ISSUE THREAD

**Issue by gdiazderadaa** [unclead/yii2-multiple-input#74]
Hi there,
I'm struggling trying to load the plugin in a modal window via ajax call. This is the response I get: 

```
   <link href="/pfc/web/assets/dc8bc3bf/css/multiple-input.css" rel="stylesheet">
   <div id="w0" class="multiple-input">
      <table class="multiple-input-list table table-condensed">
         <tbody>
            <tr class="multiple-input-list__item"></tr>
            <tr class="multiple-input-list__item"></tr>
         </tbody>
      </table>
   </div>
   <script src="/pfc/web/assets/2d68e105/jquery.js"></script>
   <script src="/pfc/web/assets/dc8bc3bf/js/jquery.multipleInput.js"></script>
   <script type="text/javascript">
      jQuery('#w0').multipleInput({
         "id":"w0","template":"<tr class=\"multiple-input-list__item\"></tr>","jsTemplates":[],"limit":"2","min":"2","attributeOptions":[]});</script>
```

The error I'm getting is: 

> synchronous  XMLHttpRequest in the main thread is deprecated.

Any ideas?
Thanks in advance

**Comment by unclead** [comment]
Please provide the code snipper to reproduce such behavior.

But i guess that the error `synchronous XMLHttpRequest in the main thread is deprecated.` does not relate to widget. Probably it relates to jquery.

I've tried to use widget in modal window and it worked correctly. Probably this issue #58 can give you some useful info

**Comment by gdiazderadaa** [comment]
```
$url = Url::to(['/componente-hardware/seriales']);
$js = <<<JS
$('form#componente-hardware-form').on('beforeSubmit', function(e) {
   var \$form = $(this);
   if ($("#cantidad").text() != null)
   {
       $.ajax({
            url: '{$url}' ,
            type:"POST",            
            data:{'number' : $("#cantidad").val()},
            dataType:"html",            
        })
        .done(function(html) {
            alert( "success" );
            $('#modal').modal('show').find('.modal-content').html(html);
        })
        .fail(function() {
            alert( "error" );
        })
   }
   // do whatever here, see the parameter \$form? is a jQuery Element to your form
})
JS
$this->registerJs($js);
```

What I wanted with this code is trigger your widget in a modal window before submitting the form, to provide additional data and once the data is fullfilled by the user, then submit the form

**Comment by unclead** [comment]
Sorry but i can't understand whole issue. Better if you provide not only js part but all parts (controller, view).
Can you show a screenshot? It helps me get whole picture of a problem because frankly i can't figure out it now.

**Comment by gdiazderadaa** [comment]
Ok, created there: [https://gist.github.com/gdiazderadaa/f6cf79895f061cd63923310c72742d1c](url)

**Comment by unclead** [comment]
Thx, i'll try to reproduce it tomorrow. But can you try to set id of widget explicity?

```
<?php
 use unclead\widgets\MultipleInput;
 echo MultipleInput::widget([
         'id' => 'seriales-input', //eg
         'limit'             => $number,
         'allowEmptyList'    => false,
         'enableGuessTitle'  => true,
         'min'               => $number,
         'name'              => 'seriales'
     ]);
?>
```

because i guess you are getting a problem with duplication of ids

**Comment by gdiazderadaa** [comment]
Already tried that without success. The error I get in the console is 

> Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/

After some researching it seems have to do with the script tags created by the plugin at rendering. Somehow jquery is not able to load the response if contains script tags...

**Comment by unclead** [comment]
I tried to reproduce and found that you have to adjust your code to achieve your aims.

Here is a code snippet which works correct for me:

**seriales.php**
```php
<?php
use unclead\widgets\MultipleInput;
use yii\bootstrap\ActiveForm;
use yii\bootstrap\Html;

$form = ActiveForm::begin([
    'id' => 'seriales-form',
    'action' => 'seriales'
]);
echo MultipleInput::widget([
    'id'                => 'seriales-input',
    'limit'             => $number,
    'allowEmptyList'    => false,
    'enableGuessTitle'  => true,
    'min'               => $number,
    'name'              => 'seriales'
]);

echo Html::submitButton('Submit', ['class' => 'btn btn-primary']);

ActiveForm::end();
```

Also i added `Modal` to the view `_form`, probably you just forgot about it in a Gist snippet 

```
<?php echo Modal::widget(['id' => 'modal']);
```
I added a note about using the widget with ajax (dcb74d512dbec2d9804dd6d7522516f061a4b03b)

**Comment by gdiazderadaa** [comment]
Thanks, will try those fixes later on

**Comment by Skatox** [comment]
I had the same problem, this issue solves when you pass the `id` attribute to MultipleInput widget.
```
<?= $form->field($model, 'attribute')->widget(MultipleInput::className(), [
      'id'  => 'attribute-input',
      \\\\\\
```

**Comment by jobir307** [comment]
fgghdfgh
