### ISSUE TITLE
Syntax error, unrecognized expression in jQuery selector

### ISSUE THREAD

**Issue by ZAYEC77** [unclead/yii2-multiple-input#78]
Hello, I have some error with multiple input.
```php
            <?= $form->field($model, 'photos')->widget(MultipleInput::className(), [
                'id' => 'photos-input',
                'columns' => [
                    [
                        'name' => 'url',
                        'type' => InputFile::className(),
                        'options' => Helper::getInputFileOptions(),
                    ]
                ],
            ]) ?>
```

InputFile [link](https://github.com/MihailDev/yii2-elfinder/blob/master/InputFile.php)
`Helper::getInputFileOptions` returns simple array.

After click on add action button I get error in devtools console:
`Uncaught Error: Syntax error, unrecognized expression: #product-photos-url-{multiple_index}`

Can help to solve this problem?

**Comment by unclead** [comment]
What version do you use? Stable or master?

**Comment by ZAYEC77** [comment]
@unclead thanks for fast response. I'm using master version.

**Comment by unclead** [comment]
Could you provide the result of `Helper::getInputFileOptions`? I need it to reproduce the bug because if i pass an emty arroy to options everything works fine

**Comment by ZAYEC77** [comment]
Sure. Please, look:
```php
            <?= $form->field($model, 'photos')->widget(MultipleInput::className(), [
                'id' => 'photos-input',
                'columns' => [
                    [
                        'name' => 'url',
                        'type' => InputFile::className(),
                        'options' => [
                            'buttonName' => Yii::t('app', 'Browse'),
                            'controller' => 'elfinder',
                            'filter' => 'image',
                            'template' => '<div class="input-group">{input}<span class="input-group-btn">{button}</span></div>',
                            'options' => ['class' => 'form-control'],
                            'buttonOptions' => ['class' => 'btn btn-default'],
                            'multiple' => false,
                        ],
                    ]
                ],
            ]) ?>
```
Value of `photos` attribute is array.

**Comment by unclead** [comment]
It is strange but i cannot reproduce the bag.
I added new property `photos` to `ExampleModel`
Then i append your snipper of code to `vendor\unclead\yii2-multiple-input\examples\views\multiple-input.php` 

```
<?php

echo $form->field($model, 'photos')->widget(MultipleInput::className(), [
    'id' => 'photos-input',
    'columns' => [
        [
            'name' => 'url',
            'type' => \mihaildev\elfinder\InputFile::className(),
            'options' => [
                'buttonName' => Yii::t('app', 'Browse'),
                'controller' => 'elfinder',
                'filter' => 'image',
                'template' => '<div class="input-group">{input}<span class="input-group-btn">{button}</span></div>',
                'options' => ['class' => 'form-control'],
                'buttonOptions' => ['class' => 'btn btn-default'],
                'multiple' => false,
            ]
        ]
    ],
]) ?>
```

and it works.

Maybe if you show me the whole code of your view file?

**Comment by unclead** [comment]
The problem occurs here: https://github.com/unclead/yii2-multiple-input/blob/master/src/assets/src/js/jquery.multipleInput.js#L157 or https://github.com/unclead/yii2-multiple-input/blob/master/src/assets/src/js/jquery.multipleInput.js#L205

you can try to watch what the value of `data.currentIndex` when you press a `add` button

You can try to change line 157 by this

```
 template = template
            .replaceAll('{multiple_index}', data.currentIndex)
            .replaceAll('%7Bmultiple_index%7D', data.currentIndex);

```

**Comment by ZAYEC77** [comment]
I clear assets and problem gone.
Thanks for help.
But I have some one else.
I want to inputs with name `Product[photos][0][url]` but widget generate name `Product[photos][url][0]`
Can I change it?

**Comment by unclead** [comment]
You can try to use a little hack - just add second column with static or hidden type.

The name is composed  as follows:
```
    public function getElementName($index, $withPrefix = true)
    {
        if (is_null($index)) {
            $index = '{multiple_index}';
        }
        $elementName = count($this->renderer->columns) > 1
            ? '[' . $index . '][' . $this->name . ']'
            : '[' . $this->name . '][' . $index . ']';
        $prefix = $withPrefix ? $this->getInputNamePrefix() : '';
        return  $prefix . $elementName;
    }
```

**Comment by ZAYEC77** [comment]
@unclead Thanks, I think extending of class will be better way for me.

**Comment by unclead** [comment]
> I think extending of class will be better way for me.

why not :smile:

**Comment by ZAYEC77** [comment]
@unclead I want to override method `getElementName` in `MultipleInputColumn` class, but it use private method `getInputNamePrefix`.
Can you change it visibility to protected for future?

**Comment by unclead** [comment]
Done 7428c9f9bce1030da996b78bdf27f89d6a88f877
