### ISSUE TITLE
MultipleInput as the column of MultipleInout (embedded)

### ISSUE THREAD

**Issue by fiamma06** [unclead/yii2-multiple-input#79]
Have a problem with input indices with using included MultipleInput

```php
<?= MultipleInput::widget([
            'model' => $model,
            'attribute' => 'questions',
            'columns' => [
                [
                    'name' => 'question',
                    'type' => 'textarea',
                ],
                [
                    'name' => 'answers',
                    'type'  => MultipleInput::class,
                    'options' => [
                        'columns' => [
                            [
                                'name' => 'right',
                                'type' => \unclead\widgets\MultipleInputColumn::TYPE_CHECKBOX
                            ],
                            [
                                'name' => 'answer'
                            ]
                        ]
                    ]
                ]
            ],
        ]);  ?>
```
First problem is double event to plus button - fixing: use stopPrepogation instead preventDefault - #80
Second problem with inputs indices i can't fix

**Comment by unclead** [comment]
Can you describe the problem with indices?

**Comment by fiamma06** [comment]
No problem. I have code MultiInput widget (M1) with 2 columns. Second column is MultiInput widget (M2)
After initialize widgets i have:
CourseExercise[data][0][question] and CourseExercise[data][0][answers][0][answer] - that right
That i click to M1 add row button i have inputs:
CourseExercise[data][2][question] and CourseExercise[data][0][answers][0][answer] - all inputs don't have right names because indexes aren't right
That i click to M2 add row button in second row:
CourseExercise[data][2][question] and CourseExercise[data][2][answers][2][answer] - inputs names not right

**Comment by unclead** [comment]
Thank you. Will try to fix it on this week.

**Comment by unclead** [comment]
Unfortunattely it is not possible fix this problem fast.
I have to extend the logic to correct work with using the widget as column.

**Comment by unclead** [comment]
Feature is implemented in master branch.
You can find an example of usage in a example folder.
