### ISSUE TITLE
Save new models

### ISSUE THREAD

**Issue by amstr1k** [unclead/yii2-multiple-input#83]
I use `TabularInput::widget` the following code controller

```php
public function actionContact()
    {
        $contacts = UserContact::find()->where(['user_id' => Yii::$app->user->identity->id])->all();

        if (Model::loadMultiple($contacts, Yii::$app->request->post()) && Model::validateMultiple($contacts)) {
            foreach ($contact as $contacts) {
                $contact->save(false);
            }
            return $this->redirect('index');
        }
    
        return $this->render('contact', ['models'=>$contacts]);
    }
```

The result is an error 
![cfadf3ea8d](https://cloud.githubusercontent.com/assets/2950344/16112158/c876b36a-33be-11e6-81b9-c85bb691d732.jpg)

**Comment by unclead** [comment]
Currently you have to pass an array to `models` property which contains at least one element, e.g. if you dont have constatcs yet you have to pass an array with bare `UserContact` entity

**Comment by unclead** [comment]
Did it solve your problem?
