### ISSUE TITLE
missing text in code

### ISSUE THREAD

**Issue by DZotya** [unclead/yii2-multiple-input#89]
Missing text in file MultipleInputColumn.php of MultipleInput widget in Yii2.
There is **MultipleInput::class** instead of **MultipleInput::className()** in line 134 in that file.

error:
_syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$'_

Yii2 version: 2.0.9
PHP version: 5.4.16
MultipleInput version: 1.3.0

**Comment by unclead** [comment]
already fixed 62acc52b4971fe50ce41c6aa1d390edd49d45f90 and i released a new version with patch yesterday

**Comment by DZotya** [comment]
Thank you very much


Üdvözlettel / Regards,
Zoltán Demeter

2016-07-19 9:01 GMT+02:00 Eugene Tupikov <notifications@github.com>:
