### ISSUE TITLE
Удаление кнопки добавления

### ISSUE THREAD

**Issue by webspec2012** [unclead/yii2-multiple-input#90]
Есть необходимость убрать кнопку добавления, и вести редактирование только из текущих значений. Есть такая возможность?

**Comment by webspec2012** [comment]
В данный момент решил вопрос посредством скрытия кнопки через JS.

**Comment by unclead** [comment]
Попробуй выставить одинаковые `min` и `limit`, тогда виджет не выводит ни кнопок добавления ни, удаления

```php
<?php
    echo $form->field($model, 'emails')->widget(MultipleInput::className(), [
        'limit'  => 3,
        'allowEmptyList' => false,
        'columns' => [
            [
                'name' => 'emails',
                'options' => [
                    'placeholder' => 'E-mail'
                ]
            ]
        ],
        'min'  => 3, // should be at least 2 rows
    ])
    ->label(false);
?>
```

![no-buttons](https://cloud.githubusercontent.com/assets/2351719/17200855/ec3429b2-54b2-11e6-8d36-5f50df924dd5.png)
